<?php
/*
 * Shipping extension for ODFL (Old Dominion Freight Lines) rated shipments
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * DISCLAIMER
 * Do not edit or add to this file if you wish to upgrade Bizuno to newer
 * versions in the future. If you wish to customize Bizuno for your
 * needs please contact PhreeSoft for more information.
 *
 * @name       Bizuno ERP
 * @author     Dave Premo, PhreeSoft <support@phreesoft.com>
 * @copyright  2008-2026, PhreeSoft, Inc.
 * @license    https://www.gnu.org/licenses/agpl-3.0.txt
 * @version    7.x Last Update: 2026-04-03
 * @filesource /controllers/shipping/carriers/odfl/odfl.php
 */

namespace bizuno;

bizAutoLoad(dirname(__FILE__)."/../../functions.php", 'viewCarrierServices');

define('ODFL_RATE_WSDL_VERSION','4');
define('ODFL_RATE_WSDL', BIZUNO_FS_LIBRARY.'controllers/shipping/carriers/odfl/RateService.wsdl');
define('ODFL_RATE_URL','https://www.odfl.com/wsRate_v4/RateService/WEB-INF/wsdl/RateService.wsdl');

class odfl
{
    public $moduleID = 'shipping';
    public $methodDir= 'carriers';
    public $code     = 'odfl';
    public $settings;
    public $rateCodes;
    public $weightUOM;
    public $dimUOM;
    public $ship_pkg;
    public $ship_pickup;
    public $ship_cod_type;
    public $confirm_type;
    public $lang     = ['title' => 'Old Dominion',
        'acronym' => 'ODFL',
        'description' => 'This method provides discounted quotes based on your ODFL contracted account. You will need an account at <a href="http://www.odfl.com" target="_blank">www.odfl.com</a> to use this carrier. Labels must be generated by hand or through their website.',
        'username' => 'Enter the ODFL user name used to log into your account at www.odfl.com',
        'password' => 'Enter the ODFL password used to log into your account at www.odfl.com',
        'account'  => 'Enter your ODFL account number provided to you by ODFL.',
        'min_weight' => 'The minimum weight of shipment to request a rate quote for this carrier.',
        'GDF' => 'LTL Speed Service Guaranteed',
        'ECF' => 'LTL Standard Service',
        'ltl_std' => 'Approx. Transit: %s Day(s)',
        'ltl_guar'=> 'Guaranteed Transit: %s Day(s)'];

    public function __construct()
    {
        $tabImage = BIZUNO_URL_FS."0/controllers/$this->moduleID/$this->methodDir/$this->code/tab_logo.png";
        $this->lang['tabTitle']= "<span class='ui-tab-image'><img src='".$tabImage."' height='30' /></span>";
        $this->getSettings();
    }

    private function getSettings()
    {
        $this->settings = ['order'=>90,'username'=>'','password'=>'','account'=>'','min_weight'=>150,'service_types'=>'GDF:ECF','default'=>'0',
            'gl_acct_c'=> getModuleCache('shipping','settings','general','gl_shipping_c'),
            'gl_acct_v'=> getModuleCache('shipping','settings','general','gl_shipping_v')];
        settingsReplace($this->settings, getMetaMethod($this->methodDir, $this->code)['settings'] ?? [], $this->settingsStructure());
        $this->settings['services'] = viewCarrierServices($this->code, $this->settings['service_types'], $this->lang);
    }

    public function settingsStructure()
    {
        $this->rateCodes = ['GDF', 'ECF'];
        $noYes    = [['id'=>'0', 'text'=>lang('no')], ['id'=>'1', 'text'=>lang('yes')]];
        $services = [];
        foreach ($this->rateCodes as $code) { $services[] = ['id'=>$code, 'text'=>$this->lang[$code]]; }
        return [
            'gl_acct_c' => ['label'=>lang('gl_shipping_c_lbl', $this->moduleID),'position'=>'after','attr'=>['type'=>'ledger','id'=>"{$this->code}_gl_acct_c",'value'=>$this->settings['gl_acct_c']]],
            'gl_acct_v' => ['label'=>lang('gl_shipping_v_lbl', $this->moduleID),'position'=>'after','attr'=>['type'=>'ledger','id'=>"{$this->code}_gl_acct_v",'value'=>$this->settings['gl_acct_v']]],
            'order'     => ['label'=>lang('sort_order'),'position'=>'after','attr'=>['type'=>'integer','size'=>'3','value'=>$this->settings['order']]],
            'username'  => ['label'=>lang('username'), 'position'=>'after','attr'=>['value'=>$this->settings['username']]],
            'password'  => ['label'=>lang('password'), 'position'=>'after','attr'=>['value'=>$this->settings['password']]],
            'account'   => ['label'=>lang('account'), 'position'=>'after','attr'=>['type'=>'integer', 'size'=>'10', 'maxlength'=>'9','value'=>$this->settings['account']]],
            'min_weight'=> ['label'=>lang('min_weight', $this->moduleID), 'position'=>'after','attr'=>['type'=>'integer','size'=>'4','maxlength'=>'3','value'=>$this->settings['min_weight']]],
            'service_types'=> ['label'=>lang('shipping_settings_default_service', $this->moduleID),'position'=>'after','values'=>$services,'attr'=>['type'=>'select','size'=>'15','multiple'=>'multiple','format'=>'array','value'=>$this->settings['service_types']]],
            'default'   => ['label'=>lang('shipping_settings_default_rate', $this->moduleID),'position'=>'after','values'=>$noYes,'attr'=>['type'=>'select','value'=>$this->settings['default']]]];
    }

    public function settingSave()
    {
        $meta   = dbMetaGet(0, "methods_{$this->methodDir}");
        $metaIdx= metaIdxClean($meta);
        $meta[$this->code]['settings']['services'] = viewCarrierServices($this->code, $this->settings['service_types'], $this->lang);
        msgDebug("\nSetting settings:services to: ".print_r($meta[$this->code]['settings']['services'], true));
        dbMetaSet($metaIdx, "methods_{$this->methodDir}", $meta);
    }

    public function rateQuote($pkg='')
    {
        $arrRates  = [];
        if ($pkg['settings']['weight'] < $this->settings['min_weight']) { return $arrRates; }
        $strXML    = $this->FormatODFLRateRequest($pkg);
        msgDebug("\nSending to url:".ODFL_RATE_URL." the string: ".print_r($strXML, true));
        $soapClient= new \SoapClient(ODFL_RATE_URL);
        $results   = $soapClient->getLTLRateEstimate($strXML);
        msgDebug ("\nReceived back from ODFL wsdl: ".print_r($results, true));
        if ($results->return->success) {
            if (strpos($this->settings['service_types'], 'ECF') !== false) $arrRates['ECF'] = [
                'title'  => $this->lang['ECF'],
                'gl_acct'=> $this->settings['gl_acct'],
                'book'   => 0, // $results->return->rateEstimate->grossFreightCharge,
                'cost'   => $results->return->rateEstimate->netFreightCharge,
                'quote'  => $results->return->rateEstimate->netFreightCharge,
                'note'   => sprintf($this->lang['ltl_std'], $results->return->destinationCities->serviceDays),
            ];
            if (strpos($this->settings['service_types'], 'GDF') !== false) $arrRates['GDF'] = [
                'title'  => $this->lang['GDF'],
                'gl_acct'=> $this->settings['gl_acct'],
                'book'   => 0, // $results->return->rateEstimate->grossFreightCharge,
                'cost'   => $results->return->rateEstimate->netFreightCharge + $results->return->rateEstimate->guaranteedServiceOption,
                'quote'  => $results->return->rateEstimate->netFreightCharge + $results->return->rateEstimate->guaranteedServiceOption,
                'note'   => sprintf($this->lang['ltl_guar'], $results->return->destinationCities->serviceDays),
            ];
        } else {
            msgAdd("ODFL Error: ".print_r($results->return->errorMessages, true));
        }
        return $arrRates;
    }

    function FormatODFLRateRequest($pkg)
    {
        // clean up the postal code as ODFL expects max of 6 characters
        $origZip = clean($pkg['bill']['postal_code'], 'alpha_num');
        $origZip = substr($origZip, 0, $pkg['bill']['country3']=='CAN' ? 6 : 5);
        $destZip = clean($pkg['ship']['postal_code'], 'alpha_num');
        $destZip = substr($destZip, 0, $pkg['ship']['country3']=='CAN' ? 6 : 5);
        $params = new \stdClass();
        $params->arg0 = new \stdClass();
        $params->arg0->odfl4MeUser          = $this->settings['username'];
        $params->arg0->odfl4MePassword      = $this->settings['password'];
        $params->arg0->odflCustomerAccount  = $this->settings['account'];
        $params->arg0->originPostalCode     = $origZip;
        $params->arg0->originCountry        = $pkg['bill']['country3'];
        $params->arg0->destinationPostalCode= $destZip;
        $params->arg0->destinationCountry   = $pkg['ship']['country3'];
        $params->arg0->freightItems         = [
            ['ratedClass' => intval($pkg['settings']['ltl_class']),
                'weight'     => intval($pkg['settings']['weight']),
//                'numberOfUnits' => 1,
            ]];
        $params->arg0->requestReferenceNumber = false;
        if ($pkg['settings']['residential']) { $params->arg0->accessorials[] = 'RDC'; }
        $params->arg0->weightUnits = getModuleCache('shipping', 'settings', 'general', 'weight_uom').'S';
        $params->arg0->pickupDateTime = biz_date('Y-m-d')."T17:00:00";
        return $params;
    }
}
