<?php
/*
 * Module api - English (US) language file
 * 
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * DISCLAIMER
 * Do not edit or add to this file if you wish to upgrade Bizuno to newer
 * versions in the future. If you wish to customize Bizuno for your
 * needs please contact PhreeSoft for more information.
 *
 * @name       Bizuno ERP
 * @author     Dave Premo, PhreeSoft <support@phreesoft.com>
 * @copyright  2008-2026, PhreeSoft, Inc.
 * @license    https://www.gnu.org/licenses/agpl-3.0.txt
 * @version    7.x Last Update: 2026-04-26
 * @filesource /controllers/api/locale/en_US/language.php
 */

$lang = [
    'title' => 'Bizuno API',
    'description' => 'Controls the defaults and credentials for all API transactions in and out of your Business.',
    'api_user_lbl'  => 'API User Email',
    'api_user_tip'  => 'Email of the existing local user account that the unauthenticated portal endpoints (orderAdd, ediCron) will execute as. Must already exist as a user (ctype_u=1) in this Business.',
    'api_pass_lbl'  => 'API Password',
    'api_pass_tip'  => 'Optional password — used by integrations that authenticate against the legacy API user/pass scheme. Leave blank if you only use the API token.',
    'api_token_lbl' => 'API Token',
    'api_token_tip' => 'Shared secret required by the unauthenticated portal endpoints (shipGetRates, orderAdd, ediCron). Pass it as `token=...` in the request POST or query string. Leave blank to disable those endpoints entirely.',
    // API Settings
    'cart_sync' => '%s Product',
    'cart_cat' => '%s Category Path',
    'cart_tags' => '%s Tags',
    'cart_slug' => '%s Slug',
    'err_io_file_open'    => 'Cannot open file (%s)',
    'err_io_file_write'   => 'Cannot write file (%s)',
    'sync_cart_missing'   => "Missing at the cart:",
    'sync_bizuno_missing' => "Products flagged to sync with PrestaShop but not found in the database:",
    'sync_success'        => "All products are in Sync!",
    'confirm_success'     => "Order status update complete, the following %s order(s) were updated: %s",
    'err_no_category'     => "Could not find category title, the category must be added at the cart level admin before this product can be uploaded!",
    'msg_test_success'    => "Connected to cart.",
    // API and Import/Export
    'upload_all' => 'Slowest - All Data (Including Images)',
    'upload_images' => 'Faster - All Data (Except Images)',
    'sync_title' => 'Synchronize Products',
    'sync_delete' => 'Delete items from cart',
    'status_title' => 'Confirm Shipments',
    'upload_title' => 'Product Bulk Upload',
    'upload_item' => 'Upload to %s',
    'upload_info' => 'Bulk upload all products flagged to be displayed in your e-store. Images are not included unless the checkbox is checked.',
    'sync_info' => 'Synchronize active products from the Bizuno database (set to show in the e-store and active) with current listings from your e-store. Any SKUs that should not be listed in the e-store are displayed. They need to be removed from the cart manually through the e-stores admin interface.',
    'status_info' => 'Confirms all shipments on the date selected from the Shipping Manager and sets the status in your e-store. Completed orders and partially shipped orders are updated. Email notifications to the customer are not sent.',
    'status_date' => 'For orders shipped on:',
    'price_sheet_desc' => 'Price Sheet to use, if any, for uploading product pricing.',
    'test_cart' => 'Test if bizuno can connect to your cart.',
    'default_mode' => 'Default server to use',
    'url_desc' => 'URL of the cart Administrator. No trailing slash please.',
    'tax_id_desc' => 'Sales Tax Rate to apply collected tax to.',
    'api_desc' => 'The following modules have defined scripts to handle importing and exporting of data into Bizuno. Each module will contain more detailed information regarding it capabilities.',
    'desc_encrypt_config' => 'Set the encryption key to use if \'Encryption Enabled\' is turned on. If setting for the first time, the old encryption key is blank.',
    'desc_security_clean' => 'This tool cleans all data security values with a expiration date prior to a selected date. WARNING: This operation cannot be undone!',
    'desc_status_seq_change' => 'Changes to the sequencing can be made here.<br />Note 1: Bizuno does not allow duplicate sequences, be sure the new starting sequence will not conflict with any currently posted values.<br />Note 2: The entry for next_deposit_num is generated by the system and uses the current date with a prefix based on the payment method selected.<br />Note 3: The entry for next_check_num can be set at the payment screen prior to posting a payment and will continue from the entered value.',
    'desc_security_clean_date' => 'Clean all values with expiration date before:',
    'auto_detect_lbl' => 'Auto Detect Sale/SO',
    'auto_detect_tip' => 'When importing orders, selects whether to allow auto-detection of a sale or sales order depending on inventory stock levels or to force a specific journal. If auto detect is selected Sales will be created only if there is sufficient stock on hand to fill the order, otherwise a Sales Order will be created.',
    ];
    
