<?php
/*
 * Shipping extension for percent rated shipments - XPO Logistics
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * DISCLAIMER
 * Do not edit or add to this file if you wish to upgrade Bizuno to newer
 * versions in the future. If you wish to customize Bizuno for your
 * needs please contact PhreeSoft for more information.
 *
 * @name       Bizuno ERP
 * @author     Dave Premo, PhreeSoft <support@phreesoft.com>
 * @copyright  2008-2026, PhreeSoft, Inc.
 * @license    https://www.gnu.org/licenses/agpl-3.0.txt
 * @version    7.x Last Update: 2026-04-03
 * @filesource /controllers/shipping/carriers/xpo/common.php
 *
 * Docs website: http://www.xpo.com/content/xml
 */

namespace bizuno;

class xpoCommon
{
    public $moduleID = 'shipping';
    public $methodDir= 'carriers';
    public $code     = 'xpo';
    public $defaults;
    public $options;
    public $settings;
    public $today;
    public $currency;
    public $test;
    public $creds;
    public $weightUOM;
    public $dimUOM;
    public $ship_pkg;
    public $ship_pickup;
    public $ship_cod_type;
    public $confirm_type;
    public $lang     = ['title' => 'XPO Logistics',
        'acronym' => 'XPO',
        'description' => 'This method provides discounted quotes based on your XPO contracted account. The credentials (user name, password, and AcctID) must be applied for through your local XPO Representative. Labels must be generated by hand or through their website, <a href="http://www.xpo.com" target="_blank">www.xpo.com</a>.',
        'username' => 'Enter the XPO user name used to register with XPO.',
        'password' => 'Enter the XPO password used to register XPO.',
        'acct_id' => 'Enter the XPO Acct Number provided to you by XPO.',
        'test_mode' => 'Mode of Operation',
        'authorization' => 'Authorization Code',
        'min_weight' => 'The minimum weight of shipment to request a rate quote for this carrier.',
        'def_ltl_class' => 'Default weight class to use for LTL shipments.',
        'def_ltl_desc'  => 'Default commodity description to use for LTL shipments.',
        'ECF' => 'LTL Ground Freight'];

    function __construct()
    {
        $this->defaults = ['order'=>90,'test_mode'=>'Y','username'=>'','password'=>'','acct_id'=>'','authorization'=>'',
            'gl_acct_c' => getModuleCache('shipping','settings','general','gl_shipping_c'),
            'gl_acct_v' => getModuleCache('shipping','settings','general','gl_shipping_v'),
            'min_weight'=>150,'ltl_class'=>125,'ltl_desc'=>'','service_types'=>'ECF','default'=>'0', 'token'=>'', 'token_date'=>''];
        $this->options = $this->getOptions();
        $this->settings= array_replace_recursive($this->defaults, getMetaMethod($this->methodDir, $this->code)['settings'] ?? []);
        $this->today   = biz_date('Y-m-d');
        $this->currency= 'USD';
        $this->test    = $this->settings['test_mode']=='Y' ? true : false;
        $this->creds   = $this->getCreds(0);
    }

    // ***************************************************************************************************************
    //                                Support functions
    // ***************************************************************************************************************
    protected function getXPO($url='', $data='', $type='auto')
    {
        global $io;
        msgDebug("\nEntering getXPO with settings token = {$this->settings['token']} and token_date = {$this->settings['token_date']}");
        if (empty($this->settings['token']) || $this->settings['token_date'] < time()) { // get a new token for today
            $this->settings['token'] = $this->getToken();
            if (!$this->settings['token']) { msgAdd("Error retrieving token from XPO, all services will be unavailable!"); return []; }
        }
        $url .= "?testMode=" . ($this->test ? 'Y' : 'N');
        msgDebug("\nXPO Request = ".print_r($data, true));
        switch ($type) {
            case 'auto': $reqType = (empty($data)) ? 'get' : 'post'; break;
            default:     $reqType = $type;
        }
        switch ($reqType) { // set the headers
            case 'get':
                $opts = ['headers'=>['Authorization'=>"Bearer {$this->settings['token']}"]];
                break;
            case 'put':
            case 'post':
                $opts = ['headers'=>['Authorization'=>"Bearer {$this->settings['token']}", 'cache-control'=>"no-cache", 'content-type'=>"application/json"]];
                break;
        }
        $response= json_decode($io->cURL($url, $data, $reqType, $opts), true);
        if (empty($response)) { return; }
        msgDebug("\nParsed XPO response = ".print_r($response, true));
        if (!empty($response['error'])) { msgAdd("XPO Error: {$response['error']['errorCode']}: {$response['error']['message']}"); return; }
        if ($response['code'] >= 200 && $response['code'] <= 300) { return $response; }
        msgAdd("XPO reponse error, HTML Error Code ".$response['code']);
        return $response;
    }

    private function getToken()
    {
        global $io;
        $opts    = ['headers'=>['authorization'=>"Basic {$this->settings['authorization']}"]];
        $request = ['grant_type'=>"password", 'username'=>$this->settings['username'], 'password'=>$this->settings['password']];
        $response= json_decode($io->cURL('https://api.ltl.xpo.com/token', $request, 'post', $opts), true);
        if (!empty($response['error'])) { msgAdd("XPO Error: {$response['error']}: {$response['error_description']}"); return; }
        $this->settings['token']     = $response['access_token'];
        $this->settings['token_date']= time()+$response['expires_in'];
        $methProps = getModuleCache($this->moduleID, $this->methodDir, $this->code);
        $methProps['settings'] = $this->settings;
        setModuleCache($this->moduleID, $this->methodDir, $this->code, $methProps);
        return $response['access_token'];
    }

    protected function getCreds($bID=0)
    {
        msgDebug("\nWorking with getCreds store id = $bID");
        $multi = getModuleCache('contacts', $this->moduleID, $this->code, 'multi_store');
        if (!$bID || !isset($multi[$bID])) { return; }
        $values = $multi[$bID];
        if (isset($values['acct_number'])) { $this->settings['acct_number'] = $values['acct_number']; }
        if (isset($values['ltl_acct_num'])){ $this->settings['ltl_acct_num']= $values['ltl_acct_num']; }
        if (isset($values['meter_number'])){ $this->settings['meter_number']= $values['meter_number']; }
        if (isset($values['auth_key']))    { $this->settings['auth_key']    = $values['auth_key']; }
        if (isset($values['auth_pw']))     { $this->settings['auth_pw']     = $values['auth_pw']; }
        if (isset($values['sp_hub']))      { $this->settings['sp_hub']      = $values['sp_hub']; }
    }

    private function getOptions()
    {
        return [
            'rateCodes' => [
                'XPO_FREIGHT_PRIORITY' => 'ECF'],
            'CODMap'    => [
                'ANY'             => lang('any'),
                'GUARANTEED_FUNDS'=> lang('guaranteed_funds', $this->moduleID),
                'CASH'            => lang('cash')],
            'PaymentMap'=> [
                'SENDER'          => lang('sender', $this->moduleID),
                'RECIPIENT'       => lang('recipient', $this->moduleID),
                'THIRD_PARTY'     => lang('third_party', $this->moduleID),
                'COLLECT'         => lang('collect', $this->moduleID)],
            'LTLClasses'=> ['0'=>lang('select'),'50'=>'50','55'=>'55','60'=>'60','65'=>'65','70'=>'70','77'=>'77.5','85'=>'85',
                '92'=>'92.5','100'=>'100','110'=>'110','125'=>'125','150'=>'150','175'=>'175','200'=>'200','250'=>'250','300'=>'300']];
    }

    protected function mapAddress($addr=[])
    {
        $output = [];
        if (!empty($addr['primary_name'])){ $output['contactInfo']['companyName']= $addr['primary_name']; }
        if (!empty($addr['contact']))     { $output['contactInfo']['fullName']   = !empty($addr['contact']) ? $addr['contact'] : $addr['primary_name']; }
        if (!empty($addr['telephone1']))  { $output['contactInfo']['phone']      = ['countryCd'=>'1','phoneNbr'=>$this->setPhone($addr['telephone1'])]; } // goofy phone number format
        if (!empty($addr['email']))       { $output['contactInfo']['email']      = ['emailAddr'=>$addr['email']]; }
        if (!empty($addr['primary_name'])){ $output['address']['careOfName']     = $addr['primary_name']; }
        if (!empty($addr['address1']))    { $output['address']['addressLine1']   = $addr['address1']; }
        if (!empty($addr['address2']))    { $output['address']['addressLine2']   = $addr['address2']; }
        if (!empty($addr['city']))        { $output['address']['cityName']       = $addr['city']; }
        if (!empty($addr['state']))       { $output['address']['stateCd']        = $addr['state']; }
        if (!empty($addr['postal_code'])) { $output['address']['postalCd']       = $addr['postal_code']; }
        if (!empty($addr['country']))     { $output['address']['countryCd']      = $addr['country']=='CA' ? 'CN' : $addr['country']; } // they goofed the ISO2 Canada code
//      if (!empty($addr['residential'])) { $output['address']['residential']    = $addr['residential']; } // Not sure how to handle residential
        return $output;
    }

    protected function setPhone($value)
    {
        $alpha = preg_replace("/[^0-9]/", "", $value);
        return substr($alpha, 0, 3).'-'.substr($alpha, 3, 7);
    }
}
