<?php
/*
 * Shipping extension for Federal Express shipments - Common API methods
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * DISCLAIMER
 * Do not edit or add to this file if you wish to upgrade Bizuno to newer
 * versions in the future. If you wish to customize Bizuno for your
 * needs please contact PhreeSoft for more information.
 *
 * @name       Bizuno ERP
 * @author     Dave Premo, PhreeSoft <support@phreesoft.com>
 * @copyright  2008-2026, PhreeSoft, Inc.
 * @license    https://www.gnu.org/licenses/agpl-3.0.txt
 * @version    7.x Last Update: 2026-04-03
 * @filesource /controllers/shipping/carriers/fedex/common.php
 */

namespace bizuno;

class fedexCommon
{
    public  $moduleID = 'shipping';
    public  $methodDir= 'carriers';
    public  $code     = 'fedex';
    public  $storeID  = 0;
    private $url_test = 'https://apis-sandbox.fedex.com'; // the rest of the url: api/rating/{version}/{requestoption}';
    private $url_prod = 'https://apis.fedex.com'; // the rest of the url: api/rating/{version}/{requestoption}';
    private $retries  = 5;
    public  $default_insurance_value = 99.00; // FedEx maximum insurance value in USD if not specified
    public  $defaults;
    public  $options;
    public  $settings;
    public  $today;
    public  $currency;
    public  $test;
    public  $urlREST;
    public $weightUOM;
    public $dimUOM;
    public $ship_pkg;
    public $ship_pickup;
    public $ship_cod_type;
    public $confirm_type;
    // These are from the developer site but LTL sandbox is really broken!!!
    public  $testShip = ['accountNumber'=>'510087020','address'=>['streetLines'=>['1202 Chalet Ln'],          'city'=>'Harrison','stateOrProvinceCode'=>'AR','postalCode'=>'72601']];
    public  $testBill = ['accountNumber'=>'510051408','address'=>['streetLines'=>['2000 Freight LTL Testing'],'city'=>'Harrison','stateOrProvinceCode'=>'AR','postalCode'=>'72601']];
    public  $lang     = ['title'=>'Federal Express',
        'acronym'      => 'FedEx',
        'description'  => 'Federal Express shipping with rates pulled directly from FedEx servers. (Requires validation with FedEx, <a href="#" onClick="jsonAction(\'shippingb/admin/signup&carrier=fedex\')">instructions</a>)',
        'instructions' => '<h3>Step 1. Develop and Test Web Services Enabled Application</h3>
This step has been completed by PhreeSoft. The remaining steps must be followed to enable label generation.
<h3>Step 2. Register for Move to Production</h3>
Start the certification process by applying for a FedEx Production Meter Number at the FedEx Developer Resource Center. <a href="http://www.fedex.com/developer" target="_blank">http://www.fedex.com/developer</a>
<h3>Step 3. Obtain Production Credentials</h3>
Obtain your production credentials (production meter number, production authentication key and production security key) online during the registration process. Your password was sent via a separate email communication.
Note: A production meter number is required for each of your locations. It is acceptable to use
the same authentication key among multiple locations. Additional meter numbers can be obtained using the Subscribe (Advanced) Web Service.
<br />Important Note: Due to the sensitivity of this information, the production authentication key is not provided in the confirmation email (Step 4). Please retain this information for your records.
<h3>Step 4. Receive Confirmation E-mail</h3>
You will receive confirmation of your registration by e-mail.
<h3>Step 5. Contact the Regional Web Integration Solutions (WIS) Support Team</h3>
Contact the Web Integration Solutions Team for your region with your application information and production credentials. Request that your application be enabled using advanced Web Services with shipping labels. (US &amp; Canada - 1.877.339.2774)
<h3>Step 6. Regional WIS Team Provides Instructions for Submitting Labels</h3>
The support team of your region sends an e-mail with instructions for certifying labels generated by your application.
<h3>Step 7. Generate and Submit Test Labels</h3>
Generate test labels associated with the application and submit the test labels to the FedEx label evaluation teams for approval.
<br />Note: The FedEx label evaluation teams require a five-day turn-around time for label evaluation.
<h3>Step 8. Label Evaluation</h3>
The FedEx label evaluation teams evaluate the submitted test labels and approves or rejects the labels. The support team member in your region contacts you regarding the approval or rejection of the submitted labels. If the labels are approved, continue to the next step. If the labels are rejected, correct the labels as instructed and resubmit them for approval.
<h3>Step 9. Regional WIS Team Enables the Application</h3>
Once the test labels are approved for production status by the label evaluation teams, the support team member for your region authorizes your profile to transmit the identified shipping label transaction and notifies you of successful certification.
<h3>Step 10. Replace URL and Credentials</h3>
Replace the test URL and test credentials with the production URL and production credentials.',
        'ship_pkg_desc' => 'To generate a label to ship a package via FedEx, Click GO and fill out the form.',
        // General
        'pkg_envelope' => 'Envelope/Letter',
        'pkg_your_box' => 'Customer Supplied',
        'pkg_tube' => 'Carrier Tube',
        'pkg_pak' => 'Carrier Pak',
        'pkg_box' => 'Carrier  Box',
        'pkg_10kg_box' => '25kg Box',
        'pkg_25kg_box' => '10kg Box',
        'service_center' => 'On Call Air',
        'station' => 'Suggested Retail Rates',
        // Configuration
        'test_mode' => 'Test/Production mode used for testing shipping labels',
        'acct_number' => 'Enter the FedEx account number to use to sign up to Web Services',
        'ltl_acct_num' => 'Enter the FedEx Freight account number to use for rate estimates, if different from the account above (Non-hybrid account). Otherwise leave blank.',
        'auth_key' => 'Enter the FedEx authentication key provided by FedEx.',
        'auth_pw' => 'Enter the FedEx developer password provided by FedEx.',
        'api_key'      => 'Enter your API key from the FedEx Developer site',
        'secret_key'   => 'Enter your Secret key from the FedEX Developer site',
        'meter_number' => 'Enter the meter number supplied to you from FedEx.',
        'sp_hub' => 'SmartPost hub ID (provided by FedEx) <a href="https://support.techdinamics.com/support/solutions/articles/230091-fedex-smartpost-hub-id-codes-information-" target="_blank">Click Here for the FedEx List</a>',
        'printer_type' => 'Type of printer to use for printing labels. PDF for plain paper, Thermal for FedEx Thermal Label Printer (See Help file before selecting Thermal printer)',
        'printer_name' => 'Sets then name of the printer to use for printing labels as defined in the printer preferences for the local workstation.',
        'err_weight_zero' => 'The package weight cannot be zero. Please correct and try again.',
        'max_weight' => 'Maximum allowed box weight, FedEx limits this to 150 pounds.',
        'max_sp_weight' => 'Maximum allowed box weight for Smart Post shipments, typically no larger than 7 pounds.',
        'def_ltl_class' => 'Default weight class to use for LTL shipments.',
        'def_ltl_desc'  => 'Default commodity description to use for LTL shipments.',
        'def_exp_multi' => 'To bill your FedEx shipments from multiple stores, enter your credentials as follows for each aditional store: PostalCode;ExpressAcct#;MeterNumber:PostalCode;ExpressAcct#;MeterNumber, etc. Stores are set in My Business -> Settings -> Bizuno settings -> Stores tab.',
        'def_ltl_multi' => 'To bill your FedEx Freight shipments from multiple stores, enter your credentials as follows for each aditional store: PostalCode;FreightAcct#:PostalCode;FreightAcct#, etc. Stores are set in My Business -> Settings -> Bizuno settings -> Stores tab.',
        'label_thermal' => 'Label size for thermal printing.',
        'label_pdf' => 'Label size for plain paper printing.',
        'recon_fee' => 'Constant amount to add to shipping rate for reconciliation to avoid flagging charges larger than estimate.',
        'recon_percent' => 'Percentage error band for reconciliation to avoid flagging shipping mismatches.',
        // Settings
        'GND' => 'Ground', // service options
        'GDR' => 'Home Delivery',
        '3DA' => 'Ground Economy',
        '1DM' => 'First Overnight',
        '1DA' => 'Priority Overnight',
        '1DP' => 'Standard Overnight',
        '2DA' => 'Express 2 Day A.M.',
        '2DP' => 'Express 2 Day',
        '3DP' => 'Express Saver',
        'I1D' => 'Int. First',
        'I2D' => 'Int. Priority',
        'IGD' => 'Int. Economy',
        '1DF' => '1 Day Freight',
        '2DF' => '2 Day Freight',
        '3DF' => '3 Day Freight',
        'GDF' => 'Gnd Priority Freight',
        'ECF' => 'Gnd Economy Freight',
        'IP1' => 'Europe First',
        'IFE' => 'Int. Economy Freight',
        'IFP' => 'Int. Priority Freight',
        // General defines
        'RATE_ERROR' => 'FedEx rate response error: ',
        'DEL_ERROR' => 'FedEx Delete Label Error: ',
        'track_in_transit' => 'Reference: %s has not been delivered, the status is: (Code %s) %s.',
        'track_status' => 'Reference: %s, Tracking #: %s Delivered: %s, Expected: %s, Cost: %s',
        'err_address_val_country' => 'The FedEx address validation tool only works in the USA',
        // Label manager
        'error_postal_code' => 'Postal Code is required to use the FedEx module'];

    function __construct()
    {
        $this->defaults = [
            'order'        => 10, 'test_mode'   =>'prod', // 'transport' =>'wsdl',
            'acct_number'  => '', 'rest_api_key'=> '', 'rest_secret'=> '',
            'service_types'=> 'GND:GDR:3DA:1DM:1DA:1DP:2DA:2DP:3DP:I1D:I2D:IGD:1DF:2DF:3DF:GDF:ECF:IP1:IFE:IFP',
            'sp_hub'       => '',   'max_sp_weight'=>7,      'max_weight'=>150,
            'printer_type' => 'PDF','printer_name' =>'zebra','label_pdf' =>'PAPER_8.5X11_TOP_HALF_LABEL','label_thermal'=>'STOCK_4X6.75_LEADING_DOC_TAB',
            'ltl_acct_num' => '',   'ltl_class'    => '125', 'ltl_desc'  =>'',
            'recon_fee'    => 3,    'recon_percent'=>0.1,    'bill_hq'   => 1,
            'gl_acct_c'    => getModuleCache('shipping','settings','general','gl_shipping_c'),
            'gl_acct_v'    => getModuleCache('shipping','settings','general','gl_shipping_v'),
            'default'      => '1', 'token'=>'', 'token_date'=>''];
        $this->options = $this->getOptions();
        $this->settings= array_replace_recursive($this->defaults, getMetaMethod($this->methodDir, $this->code)['settings'] ?? []);
        $this->today   = biz_date('Y-m-d');
        $this->currency= 'USD';
        $this->test    = $this->settings['test_mode']=='test' ? true : false;
        $this->urlREST = $this->test ? $this->url_test : $this->url_prod;
    }
    
    /**
     *
     * @param type $bID
     * @return type
     */
    protected function getCreds($bID=0)
    {
        msgDebug("\nEntering common:getCreds store id = $bID");
        $meta = !empty($bID) ? getMetaContact($bID, $this->code) : [];
        msgDebug("\nfetched meta value before clean = ".print_r($meta, true));
        metaIdxClean($meta);
        if (empty($meta['acct_number'])) { $meta['acct_number'] = $this->settings['acct_number']; } // for combo accounts
        if (empty($meta['ltl_acct_num'])){ $meta['ltl_acct_num']= $meta['acct_number']; } // for combo accounts
        if (empty($meta['gnd_econ_hub'])){ $meta['gnd_econ_hub']= $this->settings['sp_hub']; } // FedEx Ground Economy (was smart post)
        msgDebug("\nLeaving getCreds with meta = ".print_r($meta, true));
        return $meta;
    }

    /**
     *
     * @param type $pkg
     */
    protected function addCreds(&$pkg=[])
    {
        msgDebug("\nEntering addCreds.");
        $shipID = isset($pkg['shipper']['ref_id'])? $pkg['shipper']['ref_id']: $pkg['shipper']['bID']; // ref_id for rates, bID for ship
        $origID = isset($pkg['origin']['ref_id']) ? $pkg['origin']['ref_id'] : $pkg['origin']['bID'];
        $payID  = isset($pkg['payor']['ref_id'])  ? $pkg['payor']['ref_id']  : $pkg['payor']['bID'];
        $pkg['origin']['creds'] = $this->getCreds($origID); // base creds for all RESTful transactions
        $pkg['shipper']['creds']= $this->getCreds($shipID);
        $billTo = clean('ship_bill_to', 'cmd', 'post');
        switch ($billTo) {
            case 'COLLECT':
            case 'RECIPIENT':
            case 'THIRD_PARTY': $pkg['destination']['creds']['acct_number'] = clean('ship_bill_act', 'alpha_num', 'post'); break;
            default:
            case 'SENDER':      $pkg['payor']['creds'] = $this->getCreds($payID);
        }
    }

    /**
     * FedEx now uses RESTful API
     * @param string $path
     * @param array $data
     * @param string $method
     * @return type
     */
    protected function queryREST($path, $data=[], $method='post')
    {
        global $io;
        msgDebug("\nEntering queryREST with path = $path and sizeof data = ".sizeof($data));
        if (empty($this->settings['token']) || $this->settings['token_date'] < time()-10) { // get a new token for today
            $this->settings['token'] = $this->getTokenREST();
            if (empty($this->settings['token'])) { return msgAdd("Error retrieving token from FedEx, all services will be unavailable!"); }
        }
        $url     = "$this->urlREST/$path";
        $opts    = ['headers'=>['authorization'=>"Bearer {$this->settings['token']}", 'x-locale'=>'en_US', 'content-type'=>'application/json']];
        $response= false;
        msgDebug("\nSending request to url $url and data:".print_r($data, true));
        for ($i=0; $i<$this->retries; $i++) {
            $response= json_decode($io->cURL($url, json_encode($data), $method, $opts), true);
            msgDebug("\nLast response is: ".print_r($response, true));
            if (!empty($response)) { break; }
        }
        if (empty($response)) { msgAdd(sprintf(lang('err_no_communication'), $this->code).' '.$this->excNotes,); }
        return $response;
    }

    /**
     * Fetch oAuth token from fedEx servers
     * @global class $io
     * @return token if successful, null if error
     */
    private function getTokenREST()
    {
        global $io;
        $urlOauth= "$this->urlREST/oauth/token";
        $opts    = ['headers'=>['Content-Type'=>'application/x-www-form-urlencoded']];
        $data    = "grant_type=client_credentials&client_id={$this->settings['rest_api_key']}&client_secret={$this->settings['rest_secret']}";
        $response= json_decode($io->cURL($urlOauth, $data, 'post', $opts), true);
        msgDebug("\nReceived back from url $urlOauth with results: ".print_r($response, true));
        if (!empty($response['errors'])) { return msgAdd("FedEx Authentication Error: ".print_r($response['errors'], true)); }
        $this->tokenUpdate($response);
        return $response['access_token'];
    }

    private function tokenUpdate($response=[])
    {
        msgDebug("\nin tokenUpdate, read token = {$response['access_token']} and expires_in = {$response['expires_in']}");
        $token    = $response['access_token'];
        $tokenDate= time()+$response['expires_in'];
        $this->settings['token']     = $token;
        $this->settings['token_date']= $tokenDate;
        $props    = getModuleCache($this->moduleID, $this->methodDir, $this->code);
        $props['settings'] = $this->settings;
        setModuleCache($this->moduleID, $this->methodDir, $this->code, $props);
    }

    /**
     *
     * @param type $transit_time
     * @param type $res
     * @return type
     */
    protected function calculateDelivery($transit_time, $res = true) {
        $today       = getdate();
        $today_date  = biz_date('Y-m-d');
        $year        = biz_date('Y');
        $day_of_week = $today['wday'] - 1;  // 0 - Monday thru 6 - Sunday
        $holidays = [
            biz_date('Y-m-d', strtotime("1st January $year")),                 // New Years Day
            biz_date('Y-m-d', strtotime("Last Monday of May $year")),          // Memorial Day
            biz_date('Y-m-d', strtotime("4th July $year")),                    // Independence Day
            biz_date('Y-m-d', strtotime("First Monday of September $year")),   // Labor Day
            biz_date('Y-m-d', strtotime("Fourth Thursday of November $year")), // Thanksgiving Day
            biz_date('Y-m-d', strtotime("25th December $year")),               // Christmas Day
            ];
        switch ($transit_time) {
            case 'ONE_DAY':   $offset = 1; break;
            case 'TWO_DAYS':  $offset = 2; break;
            case 'THREE_DAYS':$offset = 3; break;
            case 'FOUR_DAYS': $offset = 4; break;
            case 'FIVE_DAYS': $offset = 5; break;
            case 'SIX_DAYS':  $offset = 6; break;
            case 'SEVEN_DAYS':$offset = 7; break;
            case 'EIGHT_DAYS':$offset = 8; break;
            case 'NINE_DAYS': $offset = 9; break;
        }
        if     (($day_of_week + $offset) > 9) { $offset = $offset + 4; } // passed through two weekends
        elseif (($day_of_week + $offset) > 4) { $offset = $offset + 2; } // passed through one weekend
        $curDel = biz_date('Y-m-d', strtotime("+$offset days"));
        // check for holidays
        foreach ($holidays as $holiday) {
            if ($today_date <= $holiday && $curDel >= $holiday) {
                $offset++;
                $curDel = biz_date('Y-m-d', strtotime("+$offset days"));
            }
        }
        $d = getdate(strtotime("+$offset days"));
        $delivery = biz_date('Y-m-d', mktime(0, 0, 0, $d['mon'], $d['mday'], $d['year']));
        return $delivery . ' ' . ($res ? $this->lang['del_time_RE'] : $this->lang['del_time_GD']);
    }

    protected function calculateDeliveryTime($method, $code, $res = true)
    {
        switch ($method) {
            default:
            case 'IGD':
            case '2DP':
            case '3DP': $guar_time = $res ? $this->lang['del_time_RE'] : $this->lang['del_time_2D']; break;
            case 'GND': // handled in calculateDelivery
            case 'GDR': // handled in calculateDelivery
            case 'ECF':
            case 'GDF': $guar_time = $this->lang['del_time_CM']; break;
            case 'I1D':
            case 'I2D':
            case '1DF':
            case '2DF':
            case '3DF': $guar_time = $this->lang['del_time_PR']; break;
            case '1DP':
                switch ($code) {
                    default:
                    case 'A1':
                    case 'A2':
                    case 'AA':
                    case 'A4': $guar_time = $this->lang['del_time_CM']; break;
                    case 'A3':
                    case 'A5':
                    case 'AM': $guar_time = $this->lang['del_time_PR']; break;
                }
                break;
            case '1DA':
                switch ($code) {
                    default:
                    case 'A1':
                    case 'A2':
                    case 'AA':
                    case 'A4': $guar_time = $this->lang['del_time_P1']; break;
                    case 'A3':
                    case 'A5':
                    case 'AM': $guar_time = $this->lang['del_time_PR']; break;
                    case 'RM':
                    case 'PM':
                    case 'A6': $guar_time = $this->lang['del_time_CM']; break;
                }
                break;
            case '1DE':
                switch ($code) {
                    default:
                    case 'A1': $guar_time = $this->lang['del_time_A1']; break;
                    case 'A2':
                    case 'A3': $guar_time = $this->lang['del_time_A2']; break;
                    case 'A4': $guar_time = $this->lang['del_time_A4']; break;
                    case 'A5':
                    case 'A6': $guar_time = $this->lang['del_time_A5']; break;
                }
                break;
        }
        return $guar_time;
    }

    protected function GetLTLTransit($request=[])
    {
        $request['settings']['weight']     = $request['total_weight'];
        $request['settings']['num_boxes']  = $request['total_packages'];
        $request['settings']['ship_date']  = biz_date('Y-m-d'); //biz_date('c', $request['ship_date']);
        $request['settings']['residential']= !empty($request['ship_resi']) ? 1 : 0;
        $request['settings']['ltl_class']  = $request['ltl_class'];
        $request['ship'] = [
            'primary_name'=> $request['primary_name_s'],
            'address1'    => $request['address1_s'],
            'address2'    => $request['address2_s'],
            'city'        => $request['city_s'],
            'state'       => $request['state_s'],
            'postal_code' => $request['postal_code_s'],
            'country'     => $request['country_s'],
        ];
// @TODO fix this. This method is called from ship.php and there is no method there either
return '';
        $result = $this->rateQuote($request);
        $commit = $result[$this->options['rateCodes'][$request['ship_method']]]['commit'];
        return $commit;
    }

    protected function get_error_message($code)
    {
        switch ($code) {
            case '6520': return "Your box is too heavy to transport.";
            case '6505': return "Invalid Weight entered. Enter a number greater than zero.";
            case '2430': return "Invalid Length, Width and Height. Enter a number greater than zero.";
            case '8522': return "Too many packages, please split the order or package more.";
            case '2243': return "Shipments for Home Delivery Service must be designated as Residential Delivery";
            case '2254': return "The Package is too small to ship with this method. smallest dimenstions are: ";
            case '': return "";
            case '': return "";
            default: return "Unknown code $code";
        }
    }

    /*
     * Shipment level special services for Ground/Express
     */
    public function addSpSrv(&$payload, $pkg, $is_return=false)
    {
        if (!empty($pkg['ship_saturday']) && !$is_return) {
            $payload['requestedShipment']['shipmentSpecialServices']['specialServiceTypes'][] = 'SATURDAY_DELIVERY';
        }
        if ($is_return) { // Return shipment
            $payload['requestedShipment']['shipmentSpecialServices']['specialServiceTypes'][] = 'RETURN_SHIPMENT';
            $payload['requestedShipment']['shipmentSpecialServices']['returnShipmentDetail'] = [
                'returnType'=>'PRINT_RETURN_LABEL','rma'=>['reason'=>'Recycle Program']];
        }
/*        if (!empty($pkg['cod'])) {
            $payload['requestedShipment']['shipmentSpecialServices']['shipmentCODDetail'] = [
                'returnReferenceIndicatorType'         => 'INVOICE',
                'financialInstitutionContactAndAddress'=> [
                    'address'=> ['streetLines'=>['10 FedEx Parkway','Suite 302'],'city'=>'Beverly Hills','stateOrProvinceCode'=>'CA','postalCode'=>'38127','countryCode'=>'US','residential'=>false],
                    'contact'=> ['personName' =>'person name','emailAddress'=>'email address','phoneNumber'=>'phone number','phoneExtension'=>'phone extension','companyName'=>'company name','faxNumber'=>'fax number']],
                'addTransportationChargesDetail'       => [
                    'rateType'       => 'ACCOUNT',
                    'rateLevelType'  => 'BUNDLED_RATE',
                    'chargeLevelType'=> 'CURRENT_PACKAGE',
                    'chargeType'     => 'COD_SURCHARGE'],
                'codRecipient'     => ['accountNumber'=>['value'=>123456789]],
                'remitToName'      => 'FedEx',
                'codCollectionType'=> 'ANY'];
        } */
    }

    /*
     * Shipment level special services for Freight
     */
    public function addSpSrvFrt(&$payload=[])
    {
        $extra1 = clean('extra1', 'array', 'post');
//      $payload['freightShipmentSpecialServices']['freightGuaranteeDetail'] = ['freightGuaranteeType' => 'GUARANTEED_DATE','guaranteeTimestamp'=> 'string'];
        if (!empty($extra1)) { // should be a numeric array of items
           msgDebug("\nEntering SpecialServiceTypes foreach loop with value: ".print_r($extra1, true));
           $payload['freightRequestedShipment']['freightShipmentSpecialServices']['specialServiceTypes'] = $extra1;
        }
    }

    public function addPkgs($pkg)
    {
        $arrPkgs= [];
        $insure = clean('insurance', 'integer', 'post');
        $curISO = getDefaultCurrency();
        $wtUOM  = getModuleCache('shipping', 'settings', 'general', 'weight_uom');
        $dimUOM = substr(getModuleCache('shipping', 'settings', 'general', 'dim_uom'), 0, 2);
        foreach ($pkg['packages'] as $idx => $row) {
            $box = [
                'customerReferences'=>[
                    ['customerReferenceType'=>'CUSTOMER_REFERENCE','value'=>(!empty($pkg['ship_ref_1'])?$pkg['ship_ref_1']:'PKG').'-'.($idx + 1)],
                    ['customerReferenceType'=>'INVOICE_NUMBER',    'value'=> !empty($pkg['ship_ref_1'])?$pkg['ship_ref_1']:''],
                    ['customerReferenceType'=>'P_O_NUMBER',        'value'=> !empty($pkg['ship_ref_2'])?$pkg['ship_ref_2']:'']],
//              'subPackagingType' => 'BAG',
//              'groupPackageCount'=> $i+1,
//              'contentRecord'=> [['itemNumber'=> 'string','receivedQuantity'=> 0,'description'=> 'string','partNumber'=> 'string']],
                'declaredValue'=> ['currency'=> $curISO, 'amount'=>$row['value']],
                'weight'       => ['units'   => $wtUOM,  'value' =>$row['weight']],
                'dimensions'   => ['units'   => $dimUOM, 'length'=>$row['length'], 'width'=>$row['width'], 'height'=>$row['height']],
//              'variableHandlingChargeDetail'=> ['rateType'=> 'ACCOUNT','percentValue'=>0,'rateLevelType'=>'BUNDLED_RATE','fixedValue'=>['amount'=>'100','currency'=> $this->currency)],'rateElementBasis'=> 'NET_CHARGE'],
            ];
            if (empty($insure)) { unset($box['declaredValue']); }
            $this->pkgSpSrvcs($box, $pkg); // Process Special services
            $arrPkgs[] = $box;
        }
        msgDebug("\nLeaving addPkgs with package array = ".print_r($arrPkgs, true));
        return $arrPkgs;
    }

    public function addPkgsFrt($pkg)
    {
        if (empty($pkg['ship_ref_1'])) { $pkg['ship_ref_1'] = 'NA'; }
        if (empty($pkg['frt_billed'])) { $pkg['frt_billed'] = 0; }
        $bizRef = $pkg['ship_ref_1'].'-'.round(100*$pkg['frt_billed']);
        $arrPkgs= [
            'role'                                => 'SHIPPER', // 'SHIPPER', 'CONSIGNEE'
            'totalHandlingUnits'                  => sizeof($pkg['packages']),
            'accountNumber'                       => ['value'=>$pkg['origin']['creds']['ltl_acct_num']], // for rates
            'fedExFreightAccountNumber'           => ['value'=>$pkg['origin']['creds']['ltl_acct_num']], // for labels
            'printedReferences'                   => [
                ['printedReferenceType'=>'BILL_OF_LADING',   'value'=>$bizRef],
                ['printedReferenceType'=>'SHIPPER_ID_NUMBER','value'=>$bizRef],
                ['printedReferenceType'=>'PO_NUMBER',        'value'=>$bizRef]],
            'fedExFreightBillingContactAndAddress'=> ['address'=>$this->mapAddress($pkg['payor'])],
//'printedReferences' => ['INV HERE','PO_NUMBER'], // NEED THIS TO PRONT INVOICE # and PO # on paperwordk
//          'declaredValueUnits'       => 'string',
//          'shipmentDimensions'       => ['length'=> 10,'width'=> 8,'height'=> 2,'units'=> 'IN'],
//          'clientDiscountPercent'    => 0,
//          'aliasID'                  => 'string',
//          'hazardousMaterialsOfferor'=> 'string',
//          'declaredValuePerUnit'     => ['amount'=> '100','currency'=> 'USD'],
            ];
//      $curISO = $this->currency;
        $wtUOM  = getModuleCache('shipping', 'settings', 'general', 'weight_uom');
        $dimUOM = substr(getModuleCache('shipping', 'settings', 'general', 'dim_uom'), 0, 2);
        $ltlPost = clean('ltl_class', 'alpha_num', 'post');
        $ltlClass = !empty($ltlPost) ? $ltlPost : $this->settings['ltl_class'];
        foreach ($pkg['packages'] as $idx => $pallet) {
            $box = [
                'freightClass'       => 'CLASS_'.trim($ltlClass), // use post, this is in different places for rate and ship requests
                'handlingUnits'      => 1,
                'pieces'             => 1,
//              'nmfcCode'           => 'string',
                'subPackagingType'   => 'PALLET',
                'id'                 => 'Pallet '.($idx+1),
                'description'        => !empty($pkg['ltl_desc']) ? $pkg['ltl_desc'] : 'MERCHANDISE', // FedEx says required
                'weight'             => ['units'=>$wtUOM, 'value'=>$pallet['weight']],
//              'volume'             => ['units'=> 'CUBIC_FT','value'=> 0],
//**************************************** uncomment below to test ******************
                'purchaseOrderNumber'=> !empty($pkg['ship_ref_1']) ? $pkg['ship_ref_1'] : '', // needs to be invoice num - cost
//              'id'                 => 'string',
//              'hazardousMaterials' => 'BATTERY', // HAZARDOUS_MATERIALS
                'dimensions'         => ['units'=>$dimUOM, 'length'=>$pallet['length'], 'width'=>$pallet['width'], 'height'=>$pallet['height']],
            ];
            $this->pkgSpSrvcs($box, $pkg);
            $arrPkgs['lineItem'][] = $box;
        }
        return $arrPkgs;
    }

    public function reqPkgsFrt($pkg)
    {
        $arrPkgs= [];
        $wtUOM  = getModuleCache('shipping', 'settings', 'general', 'weight_uom');
        $dimUOM = substr(getModuleCache('shipping', 'settings', 'general', 'dim_uom'), 0, 2);
        foreach($pkg['packages'] as $idx => $box) {
            $box = [
                'associatedFreightLineItems'=>[['id'=>'Pallet '.($idx+1)]],
                'weight'=> ['units'=>$wtUOM,'value'=>$box['weight']],
                'subPackagingType' => 'PALLET',
                'customerReferences' => [
                    ['customerReferenceType'=>'INVOICE_NUMBER','value'=>!empty($pkg['ship_ref_1'])?$pkg['ship_ref_1']:''],
                    ['customerReferenceType'=>'P_O_NUMBER',    'value'=>!empty($pkg['ship_ref_2'])?$pkg['ship_ref_2']:'']],
//              'groupPackageCount'=> $i+1,
//              'contentRecord'=> [['itemNumber'=> 'string','receivedQuantity'=> 0,'description'=> 'string','partNumber'=> 'string']],
//              'declaredValue'=> ['currency'=> $curISO,'amount'=>number_format($pkg['settings']['ship_ins_val']/$num_packages, 2, '.', '')],
                'dimensions'=> ['units'=> $dimUOM, 'length'=>$box['length'], 'width'=>$box['width'], 'height'=>$box['height']],
//              'variableHandlingChargeDetail'=> ['rateType'=> 'ACCOUNT','percentValue'=>0,'rateLevelType'=>'BUNDLED_RATE','fixedValue'=>['amount'=>'100','currency'=> $this->currency)],'rateElementBasis'=> 'NET_CHARGE'],
            ];
//          if (empty($pkg['settings']['insurance'] || empty($pkg['settings']['ship_ins_val'])) { unset($box['declaredValue']); }
            $arrPkgs[] = $box;
        }
        return $arrPkgs;

    }

    public function pkgSpSrvcs(&$box, $pkg)
    {
        if (empty($pkg['settings']['hazmat'])) { return; }
        $box['packageSpecialServices'] = [
            'specialServiceTypes'=> ['BATTERY'], // DANGEROUS_GOODS, BATTERY
//          'signatureOptionType'=> ['NO_SIGNATURE_REQUIRED'],
//          'alcoholDetail'=> ['alcoholRecipientType'=> 'LICENSEE','shipperAgreementType'=> 'Retailer'],
//          'packageCODDetail'=> ['codCollectionAmount'=> ['amount'=> 12.45,'currency'=>$curISO],'codCollectionType'=> 'ANY'],
//              'pieceCountVerificationBoxCount'=> 0,
            'batteryDetails'=> [
                [
                    'material'=> 'LITHIUM_METAL',
                    'regulatorySubType'=> 'IATA_SECTION_II',
                    'packing'=> 'CONTAINED_IN_EQUIPMENT',
                ],
            ],
//                'dryIceWeight'=> ['value'=> 10,'units'=>$wtUOM],
        ];
        $this->pkgHazardous($box, $pkg);
    }

    public function pkgHazardous(&$box, $pkg)
    {
        $wtUOM = getModuleCache('shipping', 'settings', 'general', 'weight_uom');
        $box['packageSpecialServices']['dangerousGoodsDetail'] = [
            'offeror'=> 'Battery Store',
            'accessibility'=> 'INACCESSIBLE', // INACCESSIBLE, ACCESSIBLE
            'emergencyContactNumber'=> '8175643243',
            'options'=> ['BATTERY'],
            'containers'=> [
                [
                    'offeror'=> 'Shipping Guy',
                    'hazardousCommodities'=> [
                        [
                            'quantity'=> ['quantityType'=> 'GROSS','amount'=> 7,'units'=> 'LB'],
                            'innerReceptacles'=> [['quantity'=> ['quantityType'=> 'GROSS','amount'=> 7,'units'=> 'LB']]],
//                          'options'=> ['labelTextOption'=> 'Override','customerSuppliedLabelText'=> 'LabelText'],
                            'description'=> [
                                'sequenceNumber'=> 1,
//                                'processingOptions'=> ['INCLUDE_SPECIAL_PROVISIONS'],
//                                'subsidiaryClasses'=> 9,
//                                'labelText'=> 'labelText',
                                'technicalName'=> 'BATTERY STORE',
//                                'packingDetails'=> ['packingInstructions'=> 'instruction','cargoAircraftOnly'=> false],
//                                'authorization'=> 'Authorization Information',
//                                'reportableQuantity'=> false,
//                                'percentage'=> 10,
//                                'id'=> 'ID',
                                'packingGroup'=> 'DEFAULT',
                                'properShippingName'=> 'LITHIUM METAL BATTERY',
                                'hazardClass'=> 9,
                            ],
                        ],
                    ],
                    'numberOfContainers'=> 1,
                    'containerType'=> 'Fiberboard Box',
                    'emergencyContactNumber'=> [
                        'areaCode'=> '817',
                        'personalIdentificationNumber'=> '5643243',
//                        'extension'=> '3245',
                        'countryCode'=> 'US',
//                        'localNumber'=> '23456',
                        ],
                    'packaging'=> ['count'=> 7,'units'=> $wtUOM],
                    'packingType'=> 'ALL_PACKED_IN_ONE',
//                    'radioactiveContainerClass'=> 'EXCEPTED_PACKAGE'
                ],
            ],
//            'packaging'=> ['count'=>7,'units'=>$wtUOM], // Number of pieces per box???
        ];
    }

    public function addEmailNotifications(&$payload, $pkg)
    {
//        msgDebug("\nEntering fedex:common:addEmailNotifications");
        // notificationEventType values: "ON_DELIVERY" "ON_EXCEPTION" "ON_SHIPMENT" "ON_TENDER" "ON_ESTIMATED_DELIVERY"
        // "ON_PICKUP_DRIVER_ARRIVED" "ON_PICKUP_DRIVER_ASSIGNED" "ON_PICKUP_DRIVER_DEPARTED" "ON_PICKUP_DRIVER_EN_ROUTE"
        // maybe more at https://developer.fedex.com/api/en-us/guides/api-reference.html#notificationeventtypes
        $payload['requestedShipment']['emailNotificationDetail'] = [
            'aggregationType'=> 'PER_SHIPMENT', // PER_SHIPMENT, PER_PACKAGE
            'personalMessage'=> 'Shipment update for your order from '.getModuleCache('bizuno', 'settings', 'company', 'primary_name').'!'];
        if (!empty($pkg['destination']['email'])) {
            $payload['requestedShipment']['emailNotificationDetail']['emailNotificationRecipients'][] = [
                'name' => $pkg['destination']['primary_name'],
                'emailNotificationRecipientType'=> 'RECIPIENT', // "BROKER" "OTHER" "RECIPIENT" "SHIPPER" "THIRD_PARTY"
                'emailAddress' => $pkg['destination']['email'],
                'notificationFormatType' => 'HTML', // "HTML" "TEXT"
                'notificationType' => 'EMAIL',
                'locale' => 'en_US', // en_US, fr_CA, es_MX, 
                'notificationEventType'=> ['ON_ESTIMATED_DELIVERY', 'ON_DELIVERY']];
        }
        if (!empty($pkg['shipper']['email'])) {
            $payload['requestedShipment']['emailNotificationDetail']['emailNotificationRecipients'][] = [
                'name'=> $pkg['shipper']['primary_name'],
                'emailNotificationRecipientType'=> 'SHIPPER',
                'emailAddress'=> $pkg['shipper']['email'],
                'notificationFormatType'=> 'HTML',
                'notificationType'=> 'EMAIL',
                'locale'=> 'en_US', // en_US, fr_CA, es_MX, 
                'notificationEventType'=> ['ON_EXCEPTION']]; // 'ON_PICKUP_DRIVER_ARRIVED', 'ON_DELIVERY'
        }
    }

    public function addCustoms(&$payload, $pkg)
    {
// Error! FedEx rate request
// Code: RATE.CUSTOMCLEARANCEDETAIL.INVALID
// Message: Customs clearance detail cannot be null.
        if (empty($pkg['origin']['address']['country']) || $pkg['origin']['address']['country']=='US') { return; }
        $payload['requestedShipment']['customsClearanceDetail'] = [
//            'commercialInvoice'=> ['shipmentPurpose'=> 'SOLD'],
//            'freightOnValue'=> 'CARRIER_RISK',
            'dutiesPayment'=> [
                'payor'=> [
                  'responsibleParty'=> [
                    'address'=> $this->mapAddress($pkg['shipper']['address']), //['streetLines'=> ['10 FedEx Parkway','Suite 302'],'city'=> 'Beverly Hills','stateOrProvinceCode'=> 'CA','postalCode'=> '90210','countryCode'=> 'US','residential'=> false],
                    'contact'=> $this->mapAddress($pkg['shipper']['contact']), //['personName' => 'John Taylor','emailAddress'=> 'sample@company.com','phoneNumber'=> '1234567890','phoneExtension'=> 'phone extension','companyName'=> 'Fedex'],
                    'accountNumber'=> ['value' => $this->settings['acct_number']],
                      ]],
//                    'address'=> ['streetLines'=> ['10 FedEx Parkway','Suite 302'],'city'=> 'Beverly Hills','stateOrProvinceCode'=> 'CA','postalCode'=> '90210','countryCode'=> 'US','residential'=> false],
//                    'contact'=> ['personName' => 'John Taylor','emailAddress'=> 'sample@company.com','phoneNumber'=> '1234567890','phoneExtension'=> 'phone extension','companyName'=> 'Fedex'],
//                    'accountNumber'=> ['value'=> '123456789']]],
                'paymentType'=> 'SENDER'], // SENDER, RECIPIENT, THIRD_PARTY, COLLECT
            'commodities'=> [ [ // per each
                'description'=> 'PRODUCTS',
                'weight'=> ['units'=> 'LB','value'=> $pkg['settings']['weight']],
                'quantity'=> $pkg['settings']['num_boxes'],
                'customsValue'=> ['amount'=>$pkg['settings']['ins_amount'],'currency'=>$this->currency],
//                'unitPrice'   => ['amount'=>'100','currency'=>$this->currency],
//                'numberOfPieces'=> 1,
//                'countryOfManufacture'=> 'US',
//                'quantityUnits'=> 'PCS',
//                'name'=> 'DOCUMENTS',
//                'harmonizedCode'=> '080211',
//                'partNumber'=> 'P1',
                ] ]
        ];
    }

    protected function mapAddress($addr=[])
    {
        $output = [];
        if (!empty($addr['address1']))   { $output['streetLines'][]      = $addr['address1']; }
        if (!empty($addr['address2']))   { $output['streetLines'][]      = $addr['address2']; }
        if (!empty($addr['city']))       { $output['city']               = $addr['city']; }
        if (!empty($addr['state']))      { $output['stateOrProvinceCode']= $addr['state']; }
        if (!empty($addr['postal_code'])){ $output['postalCode']         = $addr['postal_code']; }
        if (!empty($addr['country']))    { $output['countryCode']        = $addr['country']; }
        if (!empty($addr['residential'])){ $output['residential']        = $addr['residential']; }
        return $output;
    }

    protected function mapContact($addr=[])
    {
        $output = [];
        if (!empty($addr['primary_name'])){ $output['companyName'] = $addr['primary_name']; }
        if (!empty($addr['contact']))     { $output['personName']  = $addr['contact']; }
        if (!empty($addr['telephone1']))  { $output['phoneNumber'] = substr(str_replace(' ', '', clean($addr['telephone1'], 'numeric')), 0, 10); }
        if (!empty($addr['email']))       { $output['emailAddress']= $addr['email']; }
        return $output;
    }

    /**
     * This method creates the select values that are particular to this carrier
     */
    private function getOptions()
    {
        $options = [
            'rateCodes' => [
                'FEDEX_GROUND'          => 'GND',
                'GROUND_HOME_DELIVERY'  => 'GDR',
                'SMART_POST'            => '3DA',
                'FIRST_OVERNIGHT'       => '1DM',
                'PRIORITY_OVERNIGHT'    => '1DA',
                'STANDARD_OVERNIGHT'    => '1DP',
                'FEDEX_2_DAY'           => '2DP', // must be before FEDEX_2_DAY_AM for service matching to work
                'FEDEX_2_DAY_AM'        => '2DA',
                'FEDEX_EXPRESS_SAVER'   => '3DP',
                'INTERNATIONAL_FIRST'   => 'I1D',
                'INTERNATIONAL_PRIORITY'=> 'I2D',
                'INTERNATIONAL_ECONOMY' => 'IGD',
                'FEDEX_1_DAY_FREIGHT'   => '1DF',
                'FEDEX_2_DAY_FREIGHT'   => '2DF',
                'FEDEX_3_DAY_FREIGHT'   => '3DF',
                'FEDEX_FREIGHT_PRIORITY'=> 'GDF',
                'FEDEX_FREIGHT_ECONOMY' => 'ECF',
                'EUROPE_FIRST_INTERNATIONAL_PRIORITY'=> 'IP1',
                'INTERNATIONAL_ECONOMY_FREIGHT'      => 'IFE',
                'INTERNATIONAL_PRIORITY_FREIGHT'     => 'IFP'],
            'PickupMap' => [
                'REGULAR_PICKUP'         => lang('regular_pickup', $this->moduleID),
                'REQUEST_COURIER'        => lang('request_courier', $this->moduleID),
                'DROP_BOX'               => lang('drop_box', $this->moduleID),
                'BUSINESS_SERVICE_CENTER'=> lang('service_center', $this->moduleID),
                'STATION'                => lang('station', $this->moduleID)],
            'PackageMap' => [
                'YOUR_PACKAGING'=> $this->lang['pkg_your_box'],
                'FEDEX_BOX'     => $this->lang['pkg_box'],
                'FEDEX_PAK'     => $this->lang['pkg_pak'],
                'FEDEX_ENVELOPE'=> $this->lang['pkg_envelope'],
                'FEDEX_TUBE'    => $this->lang['pkg_tube'],
                'FEDEX_10KG_BOX'=> $this->lang['pkg_10kg_box'],
                'FEDEX_25KG_BOX'=> $this->lang['pkg_25kg_box']],
            'CODMap' => [
                'ANY'             => lang('any'),
                'GUARANTEED_FUNDS'=> lang('guaranteed_funds', $this->moduleID),
                'CASH'            => lang('cash')],
    /*
            'HandlingMap' => [
                'FIXED_AMOUNT'=> $this->lang['FIXED_AMOUNT'],
                'PERCENTAGE_OF_BASE'=> $this->lang['PERCENTAGE_OF_BASE'],
                'PERCENTAGE_OF_NET'=> $this->lang['PERCENTAGE_OF_NET'],
                'PERCENTAGE_OF_NET_EXCL_TAXES'=> $this->lang['PERCENTAGE_OF_NET_EXCL_TAXES']],
    */
            'PaymentMap' => [
                'SENDER'     => lang('sender', $this->moduleID),
                'RECIPIENT'  => lang('recipient', $this->moduleID),
                'THIRD_PARTY'=> lang('third_party', $this->moduleID),
                'COLLECT'    => lang('collect', $this->moduleID)],
            'SignatureMap' => [
//              'INDIRECT'             => lang('sig_rqd', $this->moduleID),
//              'SERVICE_DEFAULT'      => 'SERVICE_DEFAULT',
                'NO_SIGNATURE_REQUIRED'=> lang('no_sig_rqd', $this->moduleID),
                'ADULT'                => lang('adult_sig', $this->moduleID),
                'DIRECT'               => lang('sig_rqd', $this->moduleID)],
            'LTLClasses' => ['0'=>lang('select'),'050'=>'50','055'=>'55','060'=>'60','065'=>'65','070'=>'70','077'=>'77.5','085'=>'85',
                '092'=>'92.5','100'=>'100','110'=>'110','125'=>'125','150'=>'150','175'=>'175','200'=>'200','250'=>'250','300'=>'300'],
            'paperTypes' => [
                ['id'=>'PAPER_4X6',                     'text'=>lang('label_01', $this->moduleID)],
                ['id'=>'PAPER_4X8',                     'text'=>lang('label_02', $this->moduleID)],
                ['id'=>'PAPER_4X9',                     'text'=>lang('label_03', $this->moduleID)],
                ['id'=>'PAPER_7X4.75',                  'text'=>lang('label_04', $this->moduleID)],
                ['id'=>'PAPER_8.5X11_BOTTOM_HALF_LABEL','text'=>lang('label_05', $this->moduleID)],
                ['id'=>'PAPER_8.5X11_TOP_HALF_LABEL',   'text'=>lang('label_06', $this->moduleID)],
                ['id'=>'STOCK_4X6',                     'text'=>lang('label_07', $this->moduleID)],
                ['id'=>'STOCK_4X6.75_LEADING_DOC_TAB',  'text'=>lang('label_08', $this->moduleID)],
                ['id'=>'STOCK_4X6.75_TRAILING_DOC_TAB', 'text'=>lang('label_09', $this->moduleID)],
                ['id'=>'STOCK_4X8',                     'text'=>lang('label_10', $this->moduleID)],
                ['id'=>'STOCK_4X9_LEADING_DOC_TAB',     'text'=>lang('label_11', $this->moduleID)],
                ['id'=>'STOCK_4X9_TRAILING_DOC_TAB',    'text'=>lang('label_12', $this->moduleID)]]];
        return $options;
    }
}
