<?php
/*
 * Table structure for Bizuno core
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * DISCLAIMER
 * Do not edit or add to this file if you wish to upgrade Bizuno to newer
 * versions in the future. If you wish to customize Bizuno for your
 * needs please contact PhreeSoft for more information.
 *
 * @name       Bizuno ERP
 * @author     Dave Premo, PhreeSoft <support@phreesoft.com>
 * @copyright  2008-2026, PhreeSoft, Inc.
 * @license    https://www.gnu.org/licenses/agpl-3.0.txt
 * @version    7.x Last Update: 2026-01-11
 * @filesource /controllers/bizuno/install/tables.php
 */
namespace bizuno;

$iso = getDefaultCurrency();
$tables = [
    'audit_log' => ['module' => 'bizuno',
        'fields' => [
            'id'          => ['format'=>'INT(15)',     'attr'=>"NOT NULL AUTO_INCREMENT",'comment'=>'type:hidden;tag:RecordID;order:1'],
            'module_id'   => ['format'=>'VARCHAR(24)', 'attr'=>"DEFAULT ''",             'comment'=>'type:hidden;tag:ModuleID;order:2'],
            'ip_address'  => ['format'=>'VARCHAR(15)', 'attr'=>"DEFAULT ''",             'comment'=>'type:hidden;tag:IPAddress;order:3'],
            'user_id'     => ['format'=>'INT(11)',     'attr'=>"DEFAULT '0'",            'comment'=>'tag:UserID;order:10'],
            'date'        => ['format'=>'TIMESTAMP',   'attr'=>"NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP",'comment'=>'type:date;tag:LogDate;order:20'],
            'stats'       => ['format'=>'VARCHAR(32)', 'attr'=>"DEFAULT ''",             'comment'=>'type:hidden;tag:Statistics;order:30'],
            'log_entry'   => ['format'=>'VARCHAR(255)','attr'=>"DEFAULT NULL",           'comment'=>'tag:LogEntry;order:50']],
        'keys' => 'PRIMARY KEY (id), KEY (user_id)',
        'attr' => 'ENGINE=MyISAM DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci'],
    'common_meta' => ['module' => 'bizuno',
        'fields' => [
            'id'        => ['format'=>'INT(11)',    'attr'=>"NOT NULL AUTO_INCREMENT",'comment'=>'type:hidden;tag:RecordID;order:1'],
            'meta_key'  => ['format'=>'VARCHAR(64)','attr'=>"DEFAULT NULL",           'comment'=>'tag:MetaKey;order:10'],
            'meta_value'=> ['format'=>'TEXT',       'attr'=>"NULL DEFAULT ''",        'comment'=>'tag:MetaValue;order:20']],
        'keys' => 'PRIMARY KEY (id), INDEX (meta_key)',
        'attr' => 'ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci'],
    'configuration' => ['module' => 'bizuno',
        'fields' => [
            'config_key'  => ['format'=>'VARCHAR(64)','attr'=>"NOT NULL DEFAULT ''",'comment'=>'type:hidden;tag:ConfigKey;order:10'],
            'config_value'=> ['format'=>'MEDIUMTEXT', 'attr'=>"DEFAULT NULL",       'comment'=>'type:hidden;tag:ConfigValue;order:20']],
        'keys' => 'PRIMARY KEY (config_key)',
        'attr' => 'ENGINE=MyISAM DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci'],
    'contacts' => ['module' => 'contacts',
        'fields'=> [
            'id'            => ['format'=>'INT(11)',      'attr'=>"NOT NULL AUTO_INCREMENT",'comment'=> 'type:hidden;tag:RecordID;order:1',
                'import'=>false,'export'=>false,'required'=>true, 'desc'=>"Contact table ID field"],
            'ctype_b'        => ['format'=>"ENUM('0','1')",'attr'=>"DEFAULT '0'",           'comment'=>'type:checkbox;tag:branch;order:4',
                'import'=>true, 'export'=>true,'required'=>false,'desc'=>"Contact type is: Branch"],
            'ctype_c'        => ['format'=>"ENUM('0','1')",'attr'=>"DEFAULT '0'",           'comment'=>'type:checkbox;tag:customer;order:4',
                'import'=>true, 'export'=>true,'required'=>false,'desc'=>"Contact type is: Customer"],
            'ctype_e'        => ['format'=>"ENUM('0','1')",'attr'=>"DEFAULT '0'",           'comment'=>'type:checkbox;tag:employee;order:4',
                'import'=>true, 'export'=>true,'required'=>false,'desc'=>"Contact type is: Employee"],
            'ctype_i'        => ['format'=>"ENUM('0','1')",'attr'=>"DEFAULT '0'",           'comment'=>'type:checkbox;tag:crm;order:4',
                'import'=>true, 'export'=>true,'required'=>false,'desc'=>"Contact type is: CRM Contact"],
            'ctype_j'        => ['format'=>"ENUM('0','1')",'attr'=>"DEFAULT '0'",           'comment'=>'type:checkbox;tag:project;order:4',
                'import'=>true, 'export'=>true,'required'=>false,'desc'=>"Contact type is: Project"],
            'ctype_u'        => ['format'=>"ENUM('0','1')",'attr'=>"DEFAULT '0'",           'comment'=>'type:checkbox;tag:user;order:4',
                'import'=>true, 'export'=>true,'required'=>false,'desc'=>"Contact type is: User"],
            'ctype_v'        => ['format'=>"ENUM('0','1')",'attr'=>"DEFAULT '0'",           'comment'=>'type:checkbox;tag:vendor;order:4',
                'import'=>true, 'export'=>true,'required'=>false,'desc'=>"Contact type is: Vendor"],
            'attach'        => ['format'=>"ENUM('0','1')",'attr'=>"DEFAULT '0'",            'comment'=>'type:hidden;tag:Attachment;order:6',
                'import'=>false,'export'=>true,'required'=>false,'desc'=>"Attachments Present, valid values are 0 - Not Present, or 1 - Present"],
            'short_name'    => ['format'=>'VARCHAR(32)',  'attr'=>"NOT NULL DEFAULT ''",    'comment'=> 'tag:ContactID;order:8',
                'import'=>true, 'export'=>true, 'required'=>true, 'desc'=>"Contact ID, short name to identify contact, max 32 characters"],
            'inactive'      => ['format'=>"CHAR(1)",      'attr'=>"DEFAULT '0'",            'comment'=> 'type:select;tag:Status;order:10',
                'import'=>true, 'export'=>true,'required'=>false,'desc'=>"[default: 0] Contact status, 0 - Active, 1 - Active, 2 - Locked"],
            'store_id'      => ['format'=>'INT(11)',      'attr'=>"DEFAULT '0'",            'comment'=> 'type:hidden;tag:StoreID;order:12',
                'import'=>true, 'export'=>true,'required'=>false,'desc'=>"Store ID, contact record number of store associated to this contact"],
            'tax_exempt'    => ['format'=>"ENUM('0','1')",'attr'=>"DEFAULT '0'",            'comment'=>'type:checkbox;tag:TaxExempt;order:14',
                'import'=>true, 'export'=>true,'required'=>false,'desc'=>"Contact is Tax Exempt, valid values are 0 - No, or 1 - Yes"],
            'tax_rate_id'   => ['format'=>'VARCHAR(6)',   'attr'=>"DEFAULT '0'",            'comment'=> 'type:tax;tag:TaxRateID;order:16',
                'import'=>true, 'export'=>true,'required'=>false,'desc'=>"Default Sales tax, this is the ID from the tax rate settings"],
            'rep_id'        => ['format'=>'VARCHAR(16)',  'attr'=>"DEFAULT NULL",           'comment'=> 'type:select;tag:DeptRepID;order:18',
                'import'=>true, 'export'=>true,'required'=>false,'desc'=>"Department Rep ID, contact record ID of the user assigned to this account"],
            'price_sheet'   => ['format'=>'INT(11)',      'attr'=>"DEFAULT '0'",            'comment'=> 'type:select;tag:PriceSheetID;order:20',
                'import'=>true, 'export'=>true,'required'=>false,'desc'=>"Default price sheet for the user, this is a record ID from the inventory prices table"],
            'terms'         => ['format'=>'VARCHAR(32)',  'attr'=>"DEFAULT '0'",            'comment'=> 'type:hidden;tag:Terms;order:22',
                'import'=>true, 'export'=>true,'required'=>false,'desc'=>"[default: 0] Payment terms, this is an encoded value and should generally be not included in the import feed"],
            'contact_first' => ['format'=>'VARCHAR(32)',  'attr'=>"DEFAULT NULL",           'comment'=> 'tag:FirstName;order:24',
                'import'=>true, 'export'=>true,'required'=>false,'desc'=>"Contact First Name"],
            'contact_last'  => ['format'=>'VARCHAR(32)',  'attr'=>"DEFAULT NULL",           'comment'=> 'tag:LastName;order:26',
                'import'=>true, 'export'=>true,'required'=>false,'desc'=>"Contact Last Name"],
            'flex_field_1'  => ['format'=>'VARCHAR(32)',  'attr'=>"DEFAULT NULL",           'comment'=> 'tag:Title;order:28',
                'import'=>true, 'export'=>true,'required'=>false,'desc'=>"Contact title for Customers, Vendors, middle name for Employees"],
            'primary_name'  => ['format'=>'VARCHAR(48)',  'attr'=>"DEFAULT NULL",           'comment'=>'tag:PrimaryName;order:30',
                'import'=>true, 'export'=>true,'required'=>true,'desc'=>"Primary or Business Name as it appears in correspondence"],
            'contact'       => ['format'=>'VARCHAR(48)',  'attr'=>"DEFAULT NULL",           'comment'=>'tag:Contact;order:32',
                'import'=>true, 'export'=>true,'required'=>false,'desc'=>"Contact or Attention, typically a person or department"],
            'address1'      => ['format'=>'VARCHAR(48)',  'attr'=>"DEFAULT NULL",           'comment'=>'tag:Address1;order:34',
                'import'=>true, 'export'=>true,'required'=>false,'desc'=>"Address field 1"],
            'address2'      => ['format'=>'VARCHAR(48)',  'attr'=>"DEFAULT NULL",           'comment'=>'tag:Address2;order:36',
                'import'=>true, 'export'=>true,'required'=>false,'desc'=>"Address field 2"],
            'city'          => ['format'=>'VARCHAR(24)',  'attr'=>"DEFAULT NULL",           'comment'=>'tag:City;order:38',
                'import'=>true, 'export'=>true,'required'=>false,'desc'=>"City or town"],
            'state'         => ['format'=>'VARCHAR(24)',  'attr'=>"DEFAULT NULL",           'comment'=>'type:state;tag:State;order:40',
                'import'=>true, 'export'=>true,'required'=>false,'desc'=>"State of province"],
            'postal_code'   => ['format'=>'VARCHAR(10)',  'attr'=>"DEFAULT NULL",           'comment'=>'tag:PostalCode;order:42',
                'import'=>true, 'export'=>true,'required'=>false,'desc'=>"Postal or Zip code"],
            'country'       => ['format'=>'CHAR(3)',      'attr'=>"NOT NULL DEFAULT 'USA'", 'comment'=>'type:country;tag:CountryISO3;order:44',
                'import'=>true, 'export'=>true,'required'=>false,'desc'=>"Three character ISO country code, i.e. USA, JPN, CAN"],
            'email'         => ['format'=>'VARCHAR(64)',  'attr'=>"NULL DEFAULT ''",        'comment'=> 'tag:Email;order:46',
                'import'=>true, 'export'=>true,'required'=>false,'desc'=>"Unique Account Email address"],
            'email2'        => ['format'=>'VARCHAR(64)',  'attr'=>"NULL DEFAULT ''",        'comment'=> 'tag:Email2;order:48',
                'import'=>true, 'export'=>true,'required'=>false,'desc'=>"Alternate Email Address 2"],
            'email3'        => ['format'=>'VARCHAR(64)',  'attr'=>"NULL DEFAULT ''",        'comment'=> 'tag:Email3;order:50',
                'import'=>true, 'export'=>true,'required'=>false,'desc'=>"Alternate Email Address 3"],
            'email4'        => ['format'=>'VARCHAR(64)',  'attr'=>"NULL DEFAULT ''",        'comment'=> 'tag:Email4;order:52',
                'import'=>true, 'export'=>true,'required'=>false,'desc'=>"Alternate Email Address 4"],
            'telephone1'    => ['format'=>'VARCHAR(20)',  'attr'=>"NULL DEFAULT ''",        'comment'=>'tag:Telephone1;order:54',
                'import'=>true, 'export'=>true,'required'=>false,'desc'=>"Telephone number 1 (Primary)"],
            'telephone2'    => ['format'=>'VARCHAR(20)',  'attr'=>"NULL DEFAULT ''",        'comment'=>'tag:Telephone2;order:56',
                'import'=>true, 'export'=>true,'required'=>false,'desc'=>"Telephone number 1 (Primary)"],
            'telephone3'    => ['format'=>'VARCHAR(20)',  'attr'=>"NULL DEFAULT ''",        'comment'=>'tag:Telephone3;order:58',
                'import'=>true, 'export'=>true,'required'=>false,'desc'=>"Telephone number 1 (Primary)"],
            'telephone4'    => ['format'=>'VARCHAR(20)',  'attr'=>"NULL DEFAULT ''",        'comment'=>'tag:Telephone4;order:60',
                'import'=>true, 'export'=>true,'required'=>false,'desc'=>"Telephone number 1 (Primary)"],
            'website'       => ['format'=>'VARCHAR(48)',   'attr'=>"NULL DEFAULT ''",       'comment'=>'tag:Website;order:62',
                'import'=>true, 'export'=>true,'required'=>false,'desc'=>"Website address"],
            'newsletter'    => ['format'=>"ENUM('0','1')",'attr'=>"DEFAULT '0'",            'comment'=> 'type:checkbox;order:10;tag:Newsletter',
                'import'=>true, 'export'=>false,'required'=>false,'desc'=>"Enable the newsletter from your business."],
            'account_number'=> ['format'=>'VARCHAR(16)',  'attr'=>"DEFAULT NULL",           'comment'=> 'tag:AccountNumber;order:64',
                'import'=>true, 'export'=>true,'required'=>false,'desc'=>"Account Number for vendors this would be your account number assigned by the vendor"],
            'ach_enable'    => ['format'=>"ENUM('0','1')",'attr'=>"DEFAULT '0'",            'comment'=> 'type:checkbox;order:10;tag:ACHEnable',
                'import'=>true, 'export'=>false,'required'=>false,'desc'=>"Set the contact up for invoice payments via electronic ACH payments with you bank"],
            'ach_bank'      => ['format'=>"VARCHAR(32)",  'attr'=>"DEFAULT NULL",           'comment'=> 'order:12;tag:ACHBankName',
                'import'=>true, 'export'=>false,'required'=>false,'desc'=>"ACH bank name"],
            'ach_routing'   => ['format'=>"INT(11)",      'attr'=>"DEFAULT '0'",            'comment'=> 'type:integer;order:14;tag:ACHRouting',
                'import'=>true, 'export'=>false,'required'=>false,'desc'=>"ACH bank routing number"],
            'ach_account'=> ['format'=>"VARCHAR(16)",     'attr'=>"DEFAULT NULL",           'comment'=> 'type:integer;order:16;tag:ACHAccount',
                'import'=>true, 'export'=>false,'required'=>false,'desc'=>"ACH bank account number"],
            'marketplace'=> ['format'=>"ENUM('0','1')",   'attr'=>"DEFAULT '0'",            'comment'=> 'type:checkbox;order:20;tag:Marketplace',
                'import'=>true, 'export'=>true, 'required'=>false,'desc'=>"Whether the customer is a marketplace and if sales tax is withheld and remitted by the customer."],
            'gov_id_number' => ['format'=>'VARCHAR(16)',  'attr'=>"DEFAULT NULL",           'comment'=> 'tag:GovID;order:66',
                'import'=>true, 'export'=>true,'required'=>false,'desc'=>"Government ID Number, i.e. SSN for US citizens"],
            'gl_account'    => ['format'=>'VARCHAR(15)',  'attr'=>"DEFAULT NULL",           'comment'=> 'type:ledger;tag:DefaultGLAccount;order:68',
                'import'=>true, 'export'=>true,'required'=>false,'desc'=>"Default GL Account for purchases/sales"],
            'gl_acct_v'     => ['format'=>'VARCHAR(15)',  'attr'=>"DEFAULT NULL",           'comment'=> 'type:ledger;tag:DefGLAcctV;order:68',
                'import'=>true, 'export'=>true,'required'=>false,'desc'=>"Default GL Account for purchases/sales"],
            'gl_acct_c'     => ['format'=>'VARCHAR(15)',  'attr'=>"DEFAULT NULL",           'comment'=> 'type:ledger;tag:DefGLAcctC;order:69',
                'import'=>true, 'export'=>true,'required'=>false,'desc'=>"Default GL Account for purchases/sales"],
            'first_date'    => ['format'=>'DATE',         'attr'=>"DEFAULT NULL",           'comment'=> 'type:date;tag:DateCreated;order:70',
                'import'=>true,'export'=>true,'required'=>false,'desc'=>"The database record creation date for this contact"],
            'date_last'     => ['format'=>'DATE',         'attr'=>"DEFAULT NULL",           'comment'=> 'type:date;tag:DateLastEntry;order:72',
                'import'=>true,'export'=>true,'required'=>false,'desc'=>"The last update for this contact."],
            'last_date_1'   => ['format'=>'DATE',         'attr'=>"DEFAULT NULL",           'comment'=> 'type:date;tag:AltDate1;order:74',
                'import'=>true,'export'=>true,'required'=>false,'desc'=>"Last Date 1, uses vary depending on contact type"],
            'last_date_2'   => ['format'=>'DATE',         'attr'=>"DEFAULT NULL",           'comment'=> 'type:date;tag:AltDate2;order:76',
                'import'=>true,'export'=>true,'required'=>false,'desc'=>"Last Date 2, uses vary depending on contact type"]],
        'keys' => 'PRIMARY KEY (id), KEY ctype_b (ctype_b), KEY ctype_c (ctype_c), KEY ctype_e (ctype_e), KEY ctype_i (ctype_i), KEY ctype_j (ctype_j), KEY ctype_u (ctype_u), KEY ctype_v (ctype_v), KEY short_name (short_name)',
        'attr' => 'ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci',
        'extra_tabs' => true],
    'contacts_log' => ['module' => 'contacts',
        'fields'=> [
            'id'        => ['format'=>'INT(11)',    'attr'=>"NOT NULL AUTO_INCREMENT",'comment'=>'type:hidden;tag:RecordID;order:1'],
            'contact_id'=> ['format'=>'INT(11)',    'attr'=>"NOT NULL DEFAULT '0'",   'comment'=>'type:hidden;tag:ContactID;order:2'],
            'log_date'  => ['format'=>'DATETIME',   'attr'=>"DEFAULT NULL",           'comment'=>'type:date;tag:LogDate;order:10'],
            'entered_by'=> ['format'=>'INT(11)',    'attr'=>"NOT NULL DEFAULT '0'",   'comment'=>'tag:UserID;order:20'],
            'action'    => ['format'=>'VARCHAR(32)','attr'=>"DEFAULT NULL",           'comment'=>'tag:Action;order:30'],
            'notes'     => ['format'=>'TEXT',       'attr'=>"DEFAULT NULL",           'comment'=>'tag:Notes;order:40']],
        'keys' => 'PRIMARY KEY (id)',
        'attr' => 'ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci'],
    'contacts_meta' => ['module' => 'contacts',
        'fields' => [
            'id'        => ['format'=>'INT(11)',    'attr'=>"NOT NULL AUTO_INCREMENT",'comment'=>'type:hidden;tag:RecordID;order:1'],
            'ref_id'    => ['format'=>'INT(11)',    'attr'=>"NOT NULL DEFAULT '0'",   'comment'=>'type:hidden;tag:ReferenceID;order:20'],
            'meta_key'  => ['format'=>'VARCHAR(64)','attr'=>"DEFAULT NULL",           'comment'=>'tag:MetaKey;order:30'],
            'meta_value'=> ['format'=>'TEXT',       'attr'=>"NULL DEFAULT ''",        'comment'=>'tag:MetaValue;order:40']],
        'keys' => 'PRIMARY KEY (id), INDEX (ref_id), INDEX (meta_key)',
        'attr' => 'ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci'],
    'inventory' => ['module' => 'inventory',
        'fields' => [
            'id'                  => ['format'=>'INT(11)',      'attr'=>"NOT NULL AUTO_INCREMENT", 'comment'=>'type:hidden;tag:RecordID;order:1',
                'import'=>false,'export'=>false,'required'=>true,'desc'=>"Inventory table record ID"],
            'attach'              => ['format'=>"ENUM('0','1')",'attr'=>"DEFAULT '0'",             'comment'=>'type:hidden;tag:Attachment;order:4',
                'import'=>false,'export'=>true,'required'=>false,'desc'=>"Attachments Present, valid values are 0 - Not Present, or 1 - Present"],
            'sku'                 => ['format'=>'VARCHAR(24)',  'attr'=>"NOT NULL DEFAULT ''",     'comment'=>'tag:SKU;order:10',
                'import'=>true, 'export'=>true,'required'=>true,'desc'=>"Item SKU, must be unique, duplicates will override the current values."],
            'description_short'   => ['format'=>'VARCHAR(64)',  'attr'=>"DEFAULT NULL",            'comment'=>'tag:Description;order:20',
                'import'=>true, 'export'=>true,'required'=>false,'desc'=>"Required for inital import, optional thereafter"],
            'inactive'            => ['format'=>"CHAR(1)",      'attr'=>"DEFAULT '0'",             'comment'=>'type:checkbox;tag:Inactive;order:30',
                'import'=>true, 'export'=>true,'required'=>false,'desc'=>"Inactive flag, valid values are 0 - Active, or 1 - Inactive"],
            'item_weight'         => ['format'=>'FLOAT',        'attr'=>"DEFAULT '0'",             'comment'=>'tag:Weight;order:40',
                'import'=>true, 'export'=>true,'required'=>false,'desc'=>"Item weight (in default units)"],
            'buy_uom'             => ['format'=>'CHAR(4)',      'attr'=>"DEFAULT 'ea'",            'comment'=>'label:BuyUOM;order:10',
                'import'=>true, 'export'=>true,'required'=>false,'desc'=>"Item weight (in default units)"],
            'sell_uom'            => ['format'=>'CHAR(4)',      'attr'=>"DEFAULT 'ea'",            'comment'=>'label:SellUOM;order:30',
                'import'=>true, 'export'=>true,'required'=>false,'desc'=>"Item weight (in default units)"],
            'sell_qty'            => ['format'=>'FLOAT',        'attr'=>"DEFAULT '1'",             'comment'=>'label:SellQty;order:20',
                'import'=>true, 'export'=>true,'required'=>false,'desc'=>"Item weight (in default units)"],
            'invVendors'          => ['format'=>'TEXT',         'attr'=>"DEFAULT NULL",            'comment'=>'type:hidden;label:JSONInvVendors;format:stringify',
                'import'=>false, 'export'=>true,'required'=>false,'desc'=>"Item weight (in default units)"],
            'upc_code'            => ['format'=>'VARCHAR(20)',  'attr'=>"DEFAULT NULL",            'comment'=>'tag:UPCCode;order:50',
                'import'=>true, 'export'=>true,'required'=>false,'desc'=>"UPC, EAN, JAN, or ISBN. Universal standard product code."],
            'lead_time'           => ['format'=>'INT(3)',       'attr'=>"DEFAULT '1'",             'comment'=>'tag:StockLeadTime;order:60',
                'import'=>true, 'export'=>true,'required'=>false,'desc'=>"Lead time (in days) to receive product from the vendor when an order is placed."],
            'qty_stock'           => ['format'=>'FLOAT',        'attr'=>"DEFAULT '0'",             'comment'=>'tag:QtyStock;order:10',
                'import'=>false,'export'=>true,'required'=>false,'desc'=>"Quantity in Stock (calculated by the system)"],
            'qty_so'              => ['format'=>'FLOAT',        'attr'=>"DEFAULT '0'",             'comment'=>'tag:QtyOrder;order:20',
                'import'=>false,'export'=>true,'required'=>false,'desc'=>"Quantity on Sales Order (calculated by the system)"],
            'qty_alloc'           => ['format'=>'FLOAT',        'attr'=>"DEFAULT '0'",             'comment'=>'tag:QtyAllocation;order:30',
                'import'=>false,'export'=>true,'required'=>false,'desc'=>"Quantity on Allocation (calculated by the system)"],
            'qty_min'             => ['format'=>'FLOAT',        'attr'=>"DEFAULT '0'",             'comment'=>'tag:StockMinimum;order:40',
                'import'=>true, 'export'=>true,'required'=>false,'desc'=>"Minimum stock level to trigger re-order."],
            'qty_restock'         => ['format'=>'FLOAT',        'attr'=>"DEFAULT '0'",             'comment'=>'tag:StockReorder;order:50',
                'import'=>true, 'export'=>true,'required'=>false,'desc'=>"Restock quantity. Used to set quantites to reorder from vendor."],
            'qty_po'              => ['format'=>'FLOAT',        'attr'=>"DEFAULT '0'",             'comment'=>'tag:QtyPurchase;order:60',
                'import'=>false,'export'=>true,'required'=>false,'desc'=>"Quantity on Purchse Order (calculated by the system)"],
            'store_id'            => ['format'=>'INT(11)',      'attr'=>"DEFAULT '0'",             'comment'=>'type:hidden;tag:StoreID;order:52',
                'import'=>true, 'export'=>true,'required'=>false,'desc'=>"Preferred Store ID. ID value is database record id from the contacts table, default -1 (all)."],
            'description_sales'   => ['format'=>'VARCHAR(255)', 'attr'=>"DEFAULT NULL",            'comment'=>'tag:DescriptionSales;order:10',
                'import'=>true, 'export'=>true,'required'=>false,'desc'=>"Detailed description used for sales"],
            'tax_rate_id_c'       => ['format'=>'VARCHAR(6)',   'attr'=>"DEFAULT '0'",             'comment'=>'type:tax;tag:TaxRateIDCustomer;order:20',
                'import'=>true, 'export'=>true,'required'=>false,'desc'=>"[Default: 0] Tax Rate ID for customers from the db table"],
            'price_sheet_c'       => ['format'=>'INT(11)',      'attr'=>"DEFAULT '0'",             'comment'=>'type:select;tag:DefPriceSheetIDSales;order:30',
                'import'=>true, 'export'=>true,'required'=>false,'desc'=>"[Default: 0] Default price sheet for customers"],
            'block_discount'      => ['format'=>"ENUM('0','1')",'attr'=>"DEFAULT '0'",             'comment'=>'type:selNoYes;tag:BlockDiscount;order:35',
                'import'=>true, 'export'=>true,'required'=>false,'desc'=>"Block customer discounts from being applied to this specific product, valid values are 0 - No, or 1 - Discounts will not be applied"],
            'full_price'          => ['format'=>'DOUBLE',       'attr'=>"DEFAULT '0'",             'comment'=>'type:currency;tag:FullPrice;order:40',
                'import'=>true, 'export'=>true,'required'=>false,'desc'=>"Retail or List price for the item"],
            'sale_price'          => ['format'=>'DOUBLE',       'attr'=>"DEFAULT '0'",             'comment'=>'type:currency;tag:SalePrice;order:42',
                'import'=>true, 'export'=>true,'required'=>false,'desc'=>"Sale price for the item"],
            'description_purchase'=> ['format'=>'VARCHAR(255)', 'attr'=>"DEFAULT NULL",            'comment'=>'tag:DescriptionPurchase;order:10',
                'import'=>true, 'export'=>true,'required'=>false,'desc'=>"Detailed decription to use for purchases"],
            'tax_rate_id_v'       => ['format'=>'VARCHAR(6)',   'attr'=>"DEFAULT '0'",             'comment'=>'type:tax;tag:TaxRateIDVendor;order:20',
                'import'=>true, 'export'=>true,'required'=>false,'desc'=>"[Default: 0] Tax Rate ID for vendors from the db table"],
            'price_sheet_v'       => ['format'=>'INT(11)',      'attr'=>"DEFAULT '0'",             'comment'=>'type:select;tag:DefPriceSheetIDPurchase;order:30',
                'import'=>true, 'export'=>true,'required'=>false,'desc'=>"[Default: 0] Default price sheet for vendors"],
            'item_cost'           => ['format'=>'DOUBLE',       'attr'=>"DEFAULT '0'",             'comment'=>'type:currency;tag:Cost;order:40',
                'import'=>true, 'export'=>true,'required'=>false,'desc'=>"Item purchase cost"],
            'vendor_id'           => ['format'=>'INT(11)',      'attr'=>"DEFAULT '0'",             'comment'=>'type:select;tag:StockVendor;order:50',
                'import'=>true, 'export'=>true,'required'=>false,'desc'=>"Preferred vendor ID. ID value is database record id from the contacts table."],
            'inventory_type'      => ['format'=>'CHAR(2)',      'attr'=>"NOT NULL DEFAULT 'si'",   'comment'=>'type:select;tag:Type;order:10',
                'import'=>true, 'export'=>true,'required'=>false,'desc'=>"[Default: si, Stock Item] See help files for inventory type codes. Once SKU has a journal entry against it, the type cannot be changed"],
            'serialize'           => ['format'=>"ENUM('0','1')",'attr'=>"DEFAULT '0'",             'comment'=>'type:checkbox;tag:Serialized;order:20',
                'import'=>false,'export'=>false,'required'=>false,'desc'=>"Serialized Item"],
            'cost_method'         => ['format'=>"ENUM('a','f','l')",'attr'=>"NOT NULL DEFAULT 'f'",'comment'=>'type:select;tag:CostMethod;order:30',
                'import'=>true, 'export'=>true,'required'=>false,'desc'=>"[Default: f] Cost Method, choices are f (FIFO), l (LIFO), or a (Average)"],
            'gl_sales'            => ['format'=>'VARCHAR(15)',  'attr'=>"DEFAULT NULL",            'comment'=>'type:ledger;tag:GLAccountSales;order:40',
                'import'=>true, 'export'=>true,'required'=>false,'desc'=>"General Ledger Sales account ID. If left off, the default will be used."],
            'gl_inv'              => ['format'=>'VARCHAR(15)',  'attr'=>"DEFAULT NULL",            'comment'=>'type:ledger;tag:GLAccountInventory;order:50',
                'import'=>true, 'export'=>true,'required'=>false,'desc'=>"General Ledger Inventory account ID. If left off, the default will be used."],
            'gl_cogs'             => ['format'=>'VARCHAR(15)',  'attr'=>"DEFAULT NULL",            'comment'=>'type:ledger;tag:GLAccountCOGS;order:60',
                'import'=>true, 'export'=>true,'required'=>false,'desc'=>"General Ledger Cost of Good Sold account ID. If left off, the default will be used."],
            'invAccessory'        => ['format'=>'TEXT',         'attr'=>"DEFAULT NULL",            'comment'=>'type:hidden;label:Inventory Accessory;format:stringify',
                'import'=>true, 'export'=>true,'required'=>false,'desc'=>''],
            'bizProAttr'          => ['format'=>'TEXT',         'attr'=>"DEFAULT NULL",            'comment'=>'label:BizunoPro Attrs;tag:bizProAttr',
                'import'=>true, 'export'=>true,'required'=>false,'desc'=>''],
            'invImages'           => ['format'=>'TEXT',         'attr'=>"DEFAULT NULL",            'comment'=>'type:hidden;label:Inventory Images;format:stringify',
                'import'=>true, 'export'=>true,'required'=>false,'desc'=>''],
            'invOptions'          => ['format'=>'TEXT',         'attr'=>"DEFAULT NULL",            'comment'=>'type:hidden;label:Inventory Options;format:stringify',
                'import'=>true, 'export'=>true,'required'=>false,'desc'=>''],
            'image_with_path'     => ['format'=>'VARCHAR(255)', 'attr'=>"DEFAULT NULL",            'comment'=>'type:hidden;tag:Image;order:10',
                'import'=>true, 'export'=>true,'required'=>false,'desc'=>"Item image path from your default images folder. i.e. /path/to/image/image.png"],
            'creation_date'       => ['format'=>'DATETIME',     'attr'=>"DEFAULT NULL",            'comment'=>'type:date;tag:DateCreated;order:10',
                'import'=>false,'export'=>true,'required'=>false,'desc'=>"Item record creation date, format YYY-MM-DD"],
            'last_update'         => ['format'=>'DATETIME',     'attr'=>"DEFAULT NULL",            'comment'=>'type:date;tag:DateLastUpdate;order:20',
                'import'=>false,'export'=>true,'required'=>false,'desc'=>"Last update. Format YYYY-MM-DD"],
            'last_journal_date'   => ['format'=>'DATETIME',     'attr'=>"DEFAULT NULL",            'comment'=>'type:date;tag:DateLastJournal;order:30',
                'import'=>false,'export'=>true,'required'=>false,'desc'=>"Last date the item was used in a journal entry, format YYY-MM-DD"]],
        'keys' => 'PRIMARY KEY (id), KEY sku (sku)',
        'attr' => 'ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci',
        'extra_tabs' => true], // allow extra tabs to be added to table
    'inventory_history' => ['module' => 'inventory',
        'fields' => [
            'id'        => ['format'=>'INT(11)',    'attr'=>"NOT NULL AUTO_INCREMENT",'comment'=>'type:hidden;tag:RecordID;order:1'],
            'ref_id'    => ['format'=>'INT(11)',    'attr'=>"NOT NULL DEFAULT '0'",   'comment'=>'type:hidden;tag:ReferenceID;order:2'],
            'journal_id'=> ['format'=>'INT(2)',     'attr'=>"NOT NULL DEFAULT '0'",   'comment'=>'type:hidden;tag:JournalID;order:3'],
            'store_id'  => ['format'=>'INT(11)',    'attr'=>"DEFAULT '0'",            'comment'=>'type:hidden;tag:StoreID;order:4'],
            'sku'       => ['format'=>'VARCHAR(24)','attr'=>"NOT NULL DEFAULT ''",    'comment'=>'tag:SKU;order:10'],
            'qty'       => ['format'=>'FLOAT',      'attr'=>"NOT NULL DEFAULT '0'",   'comment'=>'tag:Quantity;order:20'],
            'trans_code'=> ['format'=>'VARCHAR(64)','attr'=>"DEFAULT NULL",           'comment'=>'tag:SerialNumber;order:30'],
            'remaining' => ['format'=>'FLOAT',      'attr'=>"NOT NULL DEFAULT '0'",   'comment'=>'tag:Remaining;order:40'],
            'unit_cost' => ['format'=>'DOUBLE',     'attr'=>"NOT NULL DEFAULT '0'",   'comment'=>'type:currency;tag:UnitCost;order:50'],
            'avg_cost'  => ['format'=>'DOUBLE',     'attr'=>"NOT NULL DEFAULT '0'",   'comment'=>'type:currency;tag:AverageCost;order:60'],
            'post_date' => ['format'=>'DATETIME',   'attr'=>"DEFAULT NULL",           'comment'=>'type:date;tag:PostDate;order:70']],
        'keys' => 'PRIMARY KEY (id), KEY sku (sku), KEY ref_id (ref_id), KEY remaining (remaining), INDEX (store_id), INDEX (journal_id)',
        'attr' => 'ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci'],
    'inventory_meta' => ['module' => 'inventory',
        'fields' => [
            'id'        => ['format'=>'INT(11)',    'attr'=>"NOT NULL AUTO_INCREMENT",'comment'=>'type:hidden;tag:RecordID;order:1'],
            'ref_id'    => ['format'=>'INT(11)',    'attr'=>"NOT NULL DEFAULT '0'",   'comment'=>'type:hidden;tag:ReferenceID;order:20'],
            'meta_key'  => ['format'=>'VARCHAR(64)','attr'=>"DEFAULT NULL",           'comment'=>'tag:MetaKey;order:30'],
            'meta_value'=> ['format'=>'TEXT',       'attr'=>"NULL DEFAULT ''",        'comment'=>'tag:MetaValue;order:40']],
        'keys' => 'PRIMARY KEY (id), INDEX (ref_id), INDEX (meta_key)',
        'attr' => 'ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci'],
    'journal_cogs_owed' => ['module' => 'phreebooks',
        'fields' => [
            'id'             => ['format'=>'INT(11)',    'attr'=>"NOT NULL AUTO_INCREMENT",'comment'=>'type:hidden;tag:RecordID;order:1'],
            'journal_main_id'=> ['format'=>'INT(11)',    'attr'=>"NOT NULL DEFAULT '0'",   'comment'=>'type:hidden;tag:JournalRecordID;order:2'],
            'sku'            => ['format'=>'VARCHAR(24)','attr'=>"NOT NULL DEFAULT ''",    'comment'=>'tag:SKU;order:10'],
            'qty'            => ['format'=>'FLOAT',      'attr'=>"NOT NULL DEFAULT '0'",   'comment'=>'tag:Quantity;order:20'],
            'store_id'       => ['format'=>'INT(11)',    'attr'=>"DEFAULT '0'",            'comment'=>'type:hidden;tag:StoreID;order:30'],
            'post_date'      => ['format'=>'DATE',       'attr'=>"DEFAULT NULL",           'comment'=>'type:date;tag:PostDate;order:40']],
        'keys' => 'PRIMARY KEY (id), KEY sku (sku), INDEX (store_id)',
        'attr' => 'ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci'],
    'journal_cogs_usage' => ['module' => 'phreebooks',
        'fields' => [
            'id'                  => ['format'=>'INT(11)','attr'=>"NOT NULL AUTO_INCREMENT",'comment'=>'type:hidden;tag:RecordID;order:1'],
            'journal_main_id'     => ['format'=>'INT(11)','attr'=>"NOT NULL DEFAULT '0'",   'comment'=>'type:hidden;tag:JournalRecordID;order:2'],
            'inventory_history_id'=> ['format'=>'INT(11)','attr'=>"NOT NULL DEFAULT '0'",   'comment'=>'type:hidden;tag:HistoryRecordID;order:3'],
            'qty'                 => ['format'=>'FLOAT',  'attr'=>"NOT NULL DEFAULT '0'",   'comment'=>'type:hidden;tag:Quantity;order:4']],
        'keys' => 'PRIMARY KEY (id), INDEX (journal_main_id, inventory_history_id)',
        'attr' => 'ENGINE=innodb DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci'],
    'journal_history' => ['module' => 'phreebooks',
        'fields'=> [
            'id'               => ['format'=>'INT(11)', 'attr'=>"NOT NULL AUTO_INCREMENT",'comment'=>'type:hidden;tag:RecordID;order:1'],
            'period'           => ['format'=>'INT(11)', 'attr'=>"NOT NULL DEFAULT '0'",   'comment'=>'tag:Period;order:10'],
            'gl_account'       => ['format'=>'CHAR(15)','attr'=>"NOT NULL DEFAULT ''",    'comment'=>'type:ledger;tag:GLAccount;order:20'],
            'gl_type'          => ['format'=>'INT(2)',  'attr'=>"NOT NULL DEFAULT '0'",   'comment'=>'tag:GLAccountType;order:30'],
            'beginning_balance'=> ['format'=>'DOUBLE',  'attr'=>"NOT NULL DEFAULT '0'",   'comment'=>'type:currency;tag:BeginningBalance;order:40'],
            'debit_amount'     => ['format'=>'DOUBLE',  'attr'=>"NOT NULL DEFAULT '0'",   'comment'=>'type:currency;tag:DebitAmount;order:50'],
            'credit_amount'    => ['format'=>'DOUBLE',  'attr'=>"NOT NULL DEFAULT '0'",   'comment'=>'type:currency;tag:CreditAmount;order:60'],
            'budget'           => ['format'=>'DOUBLE',  'attr'=>"DEFAULT '0'",            'comment'=>'type:currency;tag:BudgetAmount;order:70'],
            'stmt_balance'     => ['format'=>'DOUBLE',  'attr'=>"NOT NULL DEFAULT '0'",   'comment'=>'type:date;tag:StatementBalance;order:80'],
            'last_update'      => ['format'=>'DATE',    'attr'=>"DEFAULT NULL",           'comment'=>'type:date;tag:LastUpdate;order:90']],
        'keys' => 'PRIMARY KEY (id), KEY period (period), KEY gl_account (gl_account)',
        'attr' => 'ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci'],
    'journal_item' => ['module' => 'phreebooks',
        'fields'=> [
            'id'           => ['format'=>'INT(11)',      'attr'=>"NOT NULL AUTO_INCREMENT",'comment'=>'type:hidden;tag:RecordID;order:1'],
            'ref_id'       => ['format'=>'INT(11)',      'attr'=>"DEFAULT '0'",            'comment'=>'type:hidden;tag:ReferenceID;order:2'],
            'item_ref_id'  => ['format'=>'INT(11)',      'attr'=>"DEFAULT NULL",           'comment'=>'type:hidden;tag:SoPoItemRefID;order:3'],
            'gl_type'      => ['format'=>'CHAR(3)',      'attr'=>"NOT NULL DEFAULT ''",    'comment'=>'type:hidden;tag:GLType;order:4'],
            'reconciled'   => ['format'=>'INT(4)',       'attr'=>"DEFAULT '0'",            'comment'=>'type:hidden;tag:Reconciled;order:5'],
            'serialize'    => ['format'=>"ENUM('0','1')",'attr'=>"DEFAULT '0'",            'comment'=>'type:hidden;tag:Serialize;order:6'],
            'item_cnt'     => ['format'=>'INT(11)',      'attr'=>"DEFAULT '0'",            'comment'=>'tag:LineNumber;order:10'],
            'sku'          => ['format'=>'VARCHAR(24)',  'attr'=>"DEFAULT NULL",           'comment'=>'tag:SKU;order:20'],
            'qty'          => ['format'=>'FLOAT',        'attr'=>"DEFAULT '0'",            'comment'=>'tag:Quantity;order:30'],
            'description'  => ['format'=>'VARCHAR(255)', 'attr'=>"DEFAULT NULL",           'comment'=>'tag:Description;order:40'],
            'debit_amount' => ['format'=>'DOUBLE',       'attr'=>"DEFAULT '0'",            'comment'=>'type:currency;tag:DebitAmount;order:50'],
            'credit_amount'=> ['format'=>'DOUBLE',       'attr'=>"DEFAULT '0'",            'comment'=>'type:currency;tag:CreditAmount;order:60'],
            'full_price'   => ['format'=>'DOUBLE',       'attr'=>"DEFAULT '0'",            'comment'=>'type:currency;tag:PriceFull;order:65'],
            'gl_account'   => ['format'=>'VARCHAR(15)',  'attr'=>"DEFAULT NULL",           'comment'=>'type:select;tag:GLAccount;order:70'],
            'tax_rate_id'  => ['format'=>'VARCHAR(6)',   'attr'=>"DEFAULT '0'",            'comment'=>'type:tax;tag:TaxRateID;order:75'],
            'trans_code'   => ['format'=>'VARCHAR(64)',  'attr'=>"DEFAULT NULL",           'comment'=>'tag:TransactionID;order:80'],
            'post_date'    => ['format'=>'DATE',         'attr'=>"DEFAULT NULL",           'comment'=>'type:date;tag:PostDate;order:85'],
            'date_1'       => ['format'=>'DATETIME',     'attr'=>"DEFAULT NULL",           'comment'=>'type:date;tag:ItemDate1;order:90']],
        'keys' => 'PRIMARY KEY (id), KEY ref_id (ref_id), KEY sku (sku), KEY item_ref_id (item_ref_id), KEY reconciled (reconciled), KEY gl_account (gl_account)',
        'attr' => 'ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci'],
    'journal_main' => ['module' => 'phreebooks',
        'fields'=> [
            'id'            => ['format'=>'INT(11)',      'attr'=>"NOT NULL AUTO_INCREMENT",'comment'=>'type:hidden;tag:RecordID;order:1'],
            'period'        => ['format'=>'INT(2)',       'attr'=>"NOT NULL DEFAULT '0'",   'comment'=>'type:hidden;tag:Period;order:5'],
            'journal_id'    => ['format'=>'INT(2)',       'attr'=>"NOT NULL DEFAULT '0'",   'comment'=>'type:hidden;tag:JournalID;order:10'],
            'store_id'      => ['format'=>'INT(11)',      'attr'=>"DEFAULT '0'",            'comment'=>'type:hidden;tag:StoreID;order:25'],
            'description'   => ['format'=>'VARCHAR(128)', 'attr'=>"DEFAULT NULL",           'comment'=>'tag:Description;order:30'],
            'discount'      => ['format'=>'DOUBLE',       'attr'=>"DEFAULT '0'",            'comment'=>'type:currency;tag:TotalDiscount;order:55'],
            'sales_tax'     => ['format'=>'DOUBLE',       'attr'=>"DEFAULT '0'",            'comment'=>'type:currency;tag:TotalTax;order:60'],
            'freight'       => ['format'=>'DOUBLE',       'attr'=>"DEFAULT '0'",            'comment'=>'type:currency;tag:TotalShipping;order:200'],
            'total_amount'  => ['format'=>'DOUBLE',       'attr'=>"NOT NULL DEFAULT '0'",   'comment'=>'type:currency;tag:TotalAmount;order:65'],
            'purch_order_id'=> ['format'=>'VARCHAR(24)',  'attr'=>"DEFAULT NULL",           'comment'=>'tag:PurchaseOrderID;order:10'],
            'invoice_num'   => ['format'=>'VARCHAR(24)',  'attr'=>"DEFAULT NULL",           'comment'=>'tag:ReferenceNumber;order:20'],
            'closed'        => ['format'=>"ENUM('0','1')",'attr'=>"DEFAULT '0'",            'comment'=>'type:checkbox;tag:Closed;order:30'],
            'waiting'       => ['format'=>"ENUM('0','1')",'attr'=>"DEFAULT '0'",            'comment'=>'type:checkbox;tag:Waiting;order:40'],
            'post_date'     => ['format'=>'DATE',         'attr'=>"DEFAULT NULL",           'comment'=>'type:date;tag:PostDate;order:50'],
            'terminal_date' => ['format'=>'DATE',         'attr'=>"DEFAULT NULL",           'comment'=>'type:date;tag:TerminalDate;order:60'],
            'rep_id'        => ['format'=>'INT(11)',      'attr'=>"DEFAULT '0'",            'comment'=>'type:select;tag:SalesRepID;order:70'],
            'terms'         => ['format'=>'VARCHAR(32)',  'attr'=>"DEFAULT '0'",            'comment'=>'type:hidden;tag:Terms;order:80'],
            'notes'         => ['format'=>'TEXT',         'attr'=>"DEFAULT NULL",           'comment'=>'tag:Notes;order:90'],
            'contact_id_b'  => ['format'=>'INT(11)',      'attr'=>"NOT NULL DEFAULT '0'",   'comment'=>'type:hidden;tag:BillingContactID;order:2'],
            'address_id_b'  => ['format'=>'INT(11)',      'attr'=>"DEFAULT '0'",            'comment'=>'type:hidden;tag:BillingAddressID;order:3'],
            'primary_name_b'=> ['format'=>'VARCHAR(48)',  'attr'=>"DEFAULT NULL",           'comment'=>'tag:BillingPrimaryName;order:10'],
            'contact_b'     => ['format'=>'VARCHAR(48)',  'attr'=>"DEFAULT NULL",           'comment'=>'tag:BillingAttention;order:20'],
            'address1_b'    => ['format'=>'VARCHAR(48)',  'attr'=>"DEFAULT NULL",           'comment'=>'tag:BillingAddress1;order:30'],
            'address2_b'    => ['format'=>'VARCHAR(48)',  'attr'=>"DEFAULT NULL",           'comment'=>'tag:BillingAddress2;order:40'],
            'city_b'        => ['format'=>'VARCHAR(24)',  'attr'=>"DEFAULT NULL",           'comment'=>'tag:BillingCity;order:50'],
            'state_b'       => ['format'=>'VARCHAR(24)',  'attr'=>"DEFAULT NULL",           'comment'=>'tag:BillingState;order:60'],
            'postal_code_b' => ['format'=>'VARCHAR(10)',  'attr'=>"DEFAULT NULL",           'comment'=>'tag:BillingPostalCode;order:70'],
            'country_b'     => ['format'=>'CHAR(3)',      'attr'=>"DEFAULT NULL",           'comment'=>'type:country;tag:BillingCountryISO3;order:80'],
            'telephone1_b'  => ['format'=>'VARCHAR(20)',  'attr'=>"DEFAULT NULL",           'comment'=>'tag:BillingTelephone1;order:90'],
            'email_b'       => ['format'=>'VARCHAR(64)',  'attr'=>"DEFAULT NULL",           'comment'=>'tag:BillingEmail;order:95'],
            'contact_id_s'  => ['format'=>'INT(11)',      'attr'=>"DEFAULT '0'",            'comment'=>'type:hidden;tag:ShippingContactID;order:2'],
            'address_id_s'  => ['format'=>'INT(11)',      'attr'=>"DEFAULT '0'",            'comment'=>'type:hidden;tag:ShippingAddressID;order:3'],
            'primary_name_s'=> ['format'=>'VARCHAR(48)',  'attr'=>"DEFAULT NULL",           'comment'=>'tag:ShippingPrimaryName;order:10'],
            'contact_s'     => ['format'=>'VARCHAR(48)',  'attr'=>"DEFAULT NULL",           'comment'=>'tag:ShippingAttention;order:20'],
            'address1_s'    => ['format'=>'VARCHAR(48)',  'attr'=>"DEFAULT NULL",           'comment'=>'tag:ShippingAddress1;order:30'],
            'address2_s'    => ['format'=>'VARCHAR(48)',  'attr'=>"DEFAULT NULL",           'comment'=>'tag:ShippingAddress2;order:40'],
            'city_s'        => ['format'=>'VARCHAR(24)',  'attr'=>"DEFAULT NULL",           'comment'=>'tag:ShippingCity;order:50'],
            'state_s'       => ['format'=>'VARCHAR(24)',  'attr'=>"DEFAULT NULL",           'comment'=>'tag:ShippingState;order:60'],
            'postal_code_s' => ['format'=>'VARCHAR(24)',  'attr'=>"DEFAULT NULL",           'comment'=>'tag:ShippingPostalCode;order:70'],
            'country_s'     => ['format'=>'CHAR(3)',      'attr'=>"DEFAULT NULL",           'comment'=>'type:country;tag:ShippingCountryISO3;order:80'],
            'telephone1_s'  => ['format'=>'VARCHAR(20)',  'attr'=>"DEFAULT NULL",           'comment'=>'tag:ShippingTelephone1;order:90'],
            'email_s'       => ['format'=>'VARCHAR(64)',  'attr'=>"DEFAULT NULL",           'comment'=>'tag:ShippingEmail;order:95'],
            'tax_rate_id'   => ['format'=>'VARCHAR(6)',   'attr'=>"DEFAULT '0'",            'comment'=>'type:tax;tag:TaxRateID;order:10'],
            'gl_acct_id'    => ['format'=>'VARCHAR(15)',  'attr'=>"DEFAULT NULL",           'comment'=>'type:ledger;tag:GLAccount;order:10'],
            'drop_ship'     => ['format'=>"ENUM('0','1')",'attr'=>"DEFAULT '0'",            'comment'=>'type:checkbox;tag:DropShip;order:5'],
            'method_code'   => ['format'=>'VARCHAR(20)',  'attr'=>"DEFAULT NULL",           'comment'=>'type:hidden;tag:MethodID;order:2'],
            'currency'      => ['format'=>'CHAR(3)',      'attr'=>"NOT NULL DEFAULT '$iso'",'comment'=>'type:hidden;tag:CurrencyISO;order:80'],
            'currency_rate' => ['format'=>'DOUBLE',       'attr'=>"NOT NULL DEFAULT '1'",   'comment'=>'type:hidden;tag:CurrencyExchangeRate;order:81'],
            'so_po_ref_id'  => ['format'=>'INT(11)',      'attr'=>"DEFAULT '0'",            'comment'=>'type:hidden;tag:SoPoRefID;order:5'],
            'closed_date'   => ['format'=>'DATE',         'attr'=>"DEFAULT NULL",           'comment'=>'type:hidden;format:date;tag:ClosedDate;order:6'],
            'recur_id'      => ['format'=>'INT(11)',      'attr'=>"DEFAULT NULL",           'comment'=>'type:hidden;tag:RecurID;order:7'],
            'admin_id'      => ['format'=>'INT(11)',      'attr'=>"DEFAULT '0'",            'comment'=>'type:hidden;tag:UserID;order:8'],
            'printed'       => ['format'=>'INT(11)',      'attr'=>"DEFAULT '0'",            'comment'=>'type:hidden;tag:Printed;order:8'],
            'attach'        => ['format'=>"ENUM('0','1')",'attr'=>"DEFAULT '0'",            'comment'=>'type:hidden;tag:Attachment;order:9']],
        'keys' => 'PRIMARY KEY (id), KEY period (period), KEY journal_id (journal_id),
            KEY post_date (post_date), KEY closed (closed), KEY store_id (store_id), KEY contact_id_b (contact_id_b), KEY contact_id_s (contact_id_s),
            KEY invoice_num (invoice_num), KEY so_po_ref_id (so_po_ref_id)',
        'attr' => 'ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci'],
    'journal_meta' => ['module' => 'phreebooks',
        'fields' => [
            'id'        => ['format'=>'INT(11)',    'attr'=>"NOT NULL AUTO_INCREMENT",'comment'=>'type:hidden;tag:RecordID;order:1'],
            'ref_id'    => ['format'=>'INT(11)',    'attr'=>"NOT NULL DEFAULT '0'",   'comment'=>'type:hidden;tag:ReferenceID;order:20'],
            'meta_key'  => ['format'=>'VARCHAR(64)','attr'=>"DEFAULT NULL",           'comment'=>'tag:MetaKey;order:30'],
            'meta_value'=> ['format'=>'TEXT',       'attr'=>"DEFAULT NULL",           'comment'=>'tag:MetaValue;order:40']],
        'keys' => 'PRIMARY KEY (id), INDEX (ref_id), INDEX (meta_key)',
        'attr' => 'ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci'],
    'journal_periods' => ['module' => 'phreebooks',
        'fields'=> [
            'period'     => ['format'=>'INT(11)',  'attr'=>"NOT NULL DEFAULT '0'", 'comment'=>'tag:Period;order:1'],
            'fiscal_year'=> ['format'=>'INT(11)',  'attr'=>"NOT NULL DEFAULT '0'", 'comment'=>'tag:FiscalYear;order:10'],
            'start_date' => ['format'=>'DATE',     'attr'=>"DEFAULT NULL",'comment'=>'type:date;tag:StartDate;order:20'],
            'end_date'   => ['format'=>'DATE',     'attr'=>"DEFAULT NULL",'comment'=>'type:date;tag:EndDate;order:30'],
            'date_added' => ['format'=>'DATE',     'attr'=>"DEFAULT NULL",'comment'=>'type:date;tag:DateAdded;order:40'],
            'last_update'=> ['format'=>'TIMESTAMP','attr'=>"DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP",'comment'=>'type:date;tag:LastUpdate;order:50']],
        'keys' => 'PRIMARY KEY (period)',
        'attr' => 'ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci']];
